### ISSUE TITLE
Codec is missing the videos

### ISSUE THREAD

**Issue by Tomasak** [VFansss/mgs2-v-s-fix#1]
In the codec there sometimes the video. It's missing on modern PCs. Haven't tried it without WS fix, but you should mention it in known bugs.

**Comment by VFansss** [comment]
I've played it recently and I never saw missing video on codec. Can you please tell me your vga, if you have an integrated card, operative system, where you have encountered this bug and any other information you think would be useful to know?

**Comment by Tomasak** [comment]
I have nvidia gtx960 with newest drivers and running 64bit W10. It occurs in the both campaigns. Here is video how it should look like https://youtu.be/9F48R6chtJU?t=4m50s . Also the cutscene borders for 16:9 should be 0

**Comment by VFansss** [comment]
Borders cutscene button are coming in the next release...

I can't replicate the bug. Anyone has reported the same bug, and in every PC I've tried the fix video always worked like should. Doing some extra test...

**Comment by Tomasak** [comment]
Here how it looks for me http://imgur.com/ri6j2Zt
Also could you add option to not open launcher after exiting game?

**Comment by VFansss** [comment]
Strange: in every test videos look normally. Kinda hard to understand origin of the problem...thanks for the screen, I'm trying to replicate it in some ways.

Exit to desktop can be done in several ways, yes. Thinking to inserting it...

Only a question: what version of the game do you have? I've tested only european one...can be the problem, if it isn't pal version or an american one...

**Comment by Tomasak** [comment]
Is there any way to tell it from iso? I couldn't find any retail copy so i had to download it from the internet.

**Comment by VFansss** [comment]
If it doesn't have any japanese speaking or strange things I don't think it's a J-NTSC Version.
Honestly I even don't know how to differentiate from european and american version. Check on settings menu inside game: do you have an option to change subtitle speaking language? 

I'm (yet slowly, anybody pay me for this unfortunatelly ahahah) making a new version with some cool thing added. Hoping that until then I found the origin of this bug...

**Comment by Tomasak** [comment]
So, it seems to be the Multi5 version (aka PAL) due to subtitles languages availability in menu. Also tried clean version with about 6MG crack and creative alchemy to be able to run the game and problem persists. :/

**Comment by VFansss** [comment]
Make sure you choose "Full" when installing the game. Then apply the 2.0 official patch and then try to apply NVidia fix you can find here:
http://www.gamecopyworld.eu/games/pc_metal_gear_solid_2.shtml

My fix should automatically apply all of them, but worth a try.

If even tham you have the same bug...onestly I don't know :(

**Comment by Tomasak** [comment]
Tried even the 1.0 exes. Still nothing :(
My CPU is intel i5 3470 at stock clock

**Comment by VFansss** [comment]
See Issues #3

**Comment by Tomasak** [comment]
Thanks! Actually all i had to do was uninstall the law filters (The K-lite codec made me to). It works just fine with basic Windows 10 codecs, didn't even install the k lite codes.
