### ISSUE TITLE
Triggers not working

### ISSUE THREAD

**Issue by kaidantess** [VFansss/mgs2-v-s-fix#10]
I cant get the triggers to work with my xbox 360 controller, I enabled the controller with PS2 config and everything works except the triggers.
Thanks for making this fix!

**Comment by VFansss** [comment]
So strange :/

[Activate the debug mode](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) and send me the file you found in your desktop, so I can understand better the situation!

**Comment by kaidantess** [comment]
Vibration works, everything works except the triggers and yes i have tried with admin rights.
I thought it could be a driver problem but apparently i have the latest xbox controller driver.
OS: Windows 10 64bits        ...Thanks again!
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/926432/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
If vibration work (and the debug file suggest me the same) seems that all is installed in a proper place. See if padbtn.ini inside the game folder cointain this:

     00  A
     01  B
     02  X
     03  Y
    04  L2
    05  R2
    06  SEL
    07  STA
    08  EX2
    08  EX3
    09  AR
    0A  L1
    0B  R1

Let's try to found out this annoying problem. This seems long and tedious but you can complete all step in less than 3 minute.

[Try to go here](https://sites.google.com/site/0dd14lab/xinput-plus) and press the blue link "XInput Plus Ver4.14.3". It's the first blue phrase you see in the page! XInput plus is the software I used to restore trigger functionality, but in my fix I've only included the library, not the entire software.

Download the archive and unpack it on desktop, than start XInputPlus.exe.

In the bottom left you find the "Total Test" button. Press it and test if trigger are working. (Simply press them some time and see if something change!)

AfteAfter you finished, close the test window and in the top-right of the main window press "SELECT" and select the game executable inside the game folder (mgs2_sse.exe). It should prompt a select that ask if you want to load a previous saved settings. Answer YES. 

Return to test window. Now in the bottom you will find a tab named "DirectInput" with some info. On bottom of that there's "Buttons".

If you press some button they will pop up here, you can try with any button. Now press Left and Right trigger and see if 11 and 12 lights up!

**Comment by kaidantess** [comment]
11 and 12 lights up but in game they still dont work.
Gamepad and config seems to be okay, i guess it has to be the game.
Thanks for replaying!

**Comment by VFansss** [comment]
Sorry for the late reply, I'm very busy lately!

Isn't easy to debug further the question: somethings is going strangely wrong with the external library not done by me, and I run out of ideas :sob:  

We cut it short: you come here to play the game and you WILL play the game, regardless of poltergeist inside Windows.

Download [Antimicro 2.23 Portable](https://github.com/AntiMicro/antimicro/releases/download/2.23/antimicro-2.23-win32.portable.zip) and extract it into your desktop.

Run Antimicro.exe with Admin Rights, press LOAD and load [this configuration](https://mega.nz/#!615VFKyT!o_aIf1X6hL6AkK1T6qrkxshwdpWPS3a2CZOUok9Spls).

Then it should work for sure!
I've thinked for ages to include in some ways Antimicro inside my fix, but I can't do it cause licence with others people work!

Tell me if it work, and sorry for that!
