### ISSUE TITLE
Solidus torture on euro extreme turbo feature

### ISSUE THREAD

**Issue by Jmc-MGS** [VFansss/mgs2-v-s-fix#102]
**Is your feature request related to a problem? Please describe.**
This fix has enabled a community of speedrunners to compete with the game but the solidus torture sequence simply puts people off running the game. 

**Describe the solution you'd like**
We would love a feature within the launcher of the game to enable you to simply hold the triangle/Y button on the controller, like a turbo pad and pass the torture. Alternatively set the torture sequence to the same duration and health depletion as normal mode. 

**Describe alternatives you've considered**
We have considered allowing turbo controllers but by doing this we risk runners skipping cutscenes frame perfectly, so ideally an option that can be toggled on or off that is available to everyone with the fix would be the best case scenario

**Additional context**
This would open the game up to many skilled runners who simply cannot mash and we feel it is a pointless barrier for entry, it has been fixed in the HD collection to use very easy torture duration and health recovery. 

It would be an amazing quality of life addition to what is already one of the best fixes I've ever used. Thank you for your time and amazing work!

**Comment by VFansss** [comment]
I can't say this isn't an interesting features.

I will probably do it: that damned torture is probably the most infamous button smash section in the entire history of gaming.

I can't tell an ETA or how I could accomplish that, but is certainly something I want to do 😄

**Comment by VFansss** [comment]
Wrote by eol on Discord:

```
I found a way without the loader. You can change the behavior of the game so that the oxygen value will not decrease during torture.
You need to change one byte in one file. It will only affect the torture scene.
Change the value 0xc4 to 0xc1 at offset 0x3026 in the file cdrom.img\stage\w51a\scenerio.gcx
```

**Comment by SammyCola** [comment]
Apologies for re-opening this issue, but I have created a mod that doesn't rely on editing the GCX file, preserving your game install (can't tell you how many times I've created a broken install due to modding in the cdrom.img folder).

Maybe this can be tested further, then integrated into the main fix?

https://github.com/UltimateNova1203/mgs2-torture

**Comment by VFansss** [comment]
Wow, fantastic!

For sure this will be less painful than writing back and forth on the actual game files.

I will implement it and test it the next time I have time to work on the V's backlog.

Thanks <3
