### ISSUE TITLE
Issue upon start

### ISSUE THREAD

**Issue by ankitkumar2003** [VFansss/mgs2-v-s-fix#104]
Hi,

So, I've read the manual and followed the steps to the best of my ability. Initially the program was saying that my VGA set by my computer and the VGA chosen by V's fix were different, but I couldn't figure out why since there's only one VGA in my computer to choose from. Even after I managed to sort that out, I'm getting an error when I click the 'start' button, where is says "failed creating IDirectSound8". I looked up previous fixes to the problem and they don't seem to have worked. Thanks a bunch for your help!
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/4142790/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
> So, I've read the manual and followed the steps to the best of my ability

You have done everything like it should, so don't worry :)
 
> Initially the program was saying that my VGA set by my computer and the VGA chosen by V's fix were different, but I couldn't figure out why since there's only one VGA in my computer to choose from.

In fact, from the log you sent me I can read that V's Fix can only detect one VGA from your system (the 1080 Ti). I will try to figure it out...

> Even after I managed to sort that out

Just for curiosity: how?

> I'm getting an error when I click the 'start' button, where is says "failed creating IDirectSound8".

That is an issue regarding the "audio" part of the game, that can't adapt to the default audio adapter.

I've two possible solution of that, please try them in order and see if one work. If not, try the other:

1. Go to [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#common-problems--common-solutions) page and do the solution addressed for the issue I cannot ear any audio. No music, no effect, nothing. But everything else work as it should". Apply that on windows, and then simply start the game.

2. Delete the files "dsound.dll" and "dsound.ini" from the "bin" game folder of the game. Then start it. (NB: If it doesn't work, delete "_audio_fix_applied.sss" from the game folder to restore the files the next time the fix start, or simply restore them from the recycle bin if you want).

Try them and we will try to solve this strange issue.

Sorry for the late reply (I'm busy as hell with work, lately), and keep me informed!

**Comment by VFansss** [comment]
Similar issues has been solved meanwhile and I've updated the wiki with new solutions, so maybe this isn't needed anymore.
