### ISSUE TITLE
Black screen when game starts

### ISSUE THREAD

**Issue by CaioMel360** [VFansss/mgs2-v-s-fix#105]
I have a problem with my sti is 1422 notebook with Core I7, as soon as I press play, the game window appears, but it is completely black but the konami logo or audio does not appear, help me
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/4175034/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
Seems that there's a problem with .dll extraction. From the .log:

> [ EXCEPTION ] Message:O acesso ao caminho 'C:\Games\bin\d3d8.dll' foi negado.

Try to delete d3d8.dll manually and then press the SAVE button from the fix.

**Comment by CaioMel360** [comment]
Parece que não funcionou, vou mandar o log

**Comment by VFansss** [comment]
[Probably doing this would probably solve the issue](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix)

Better late than ever.
