### ISSUE TITLE
Soft sounds

### ISSUE THREAD

**Issue by Qrab117** [VFansss/mgs2-v-s-fix#106]
Sound is soft its almost hearable even with my audio on max

**Comment by VFansss** [comment]
Sorry for the late response!

Can you please check that from the main game menu (where you have NEW GAME and LOAD GAME) --> SETTINGS, the SE and MUSIC volume is at 15?

**Comment by Qrab117** [comment]
Yea it's at 15

**Comment by VFansss** [comment]
I've updated the `Troubleshooting & Debug mode` page with solutions that could address this.

Until next time...I will close this.
