### ISSUE TITLE
mben67 - Sharing my layout for keyboard

### ISSUE THREAD

**Issue by mben67** [VFansss/mgs2-v-s-fix#107]
Hi, i made a new Layout for Keyboard, is based in the ps2 controller distribution buttons, ejem:

NUMPAD8  = Y
NUMPAD2  = A
NUMPAD6  = B
NUMPAD4 = X

Walk= W,  S, A, D

Walk Slow = NUMPAD0

Katana= Arrow Keys

Lower Weapon without fire:  Left Shift for Pistols & Left Control for Machine Guns or you can use walk slow button to lower both weapons

Start: Tab

Select: Enter

L1 = Q  

L2 = V

R1 = E

R2 = Space

First Person View (Toggle) =  NUMPAD5 

First Person View (Normal) = Space 

Just Copy and Paste the next layout in the  kb.ini and kbs.ini

The only downside is in the first person view missions, its a pain in the  ass move and look, so feel free to enhanced this layout and share the fixes here.

Enjoy!!

W                 U
S                  D
D                  R
A                  L
LEFT             RL
RIGHT          RR
Q                  L1
V                   L2
E                   R1
RETURN       SEL
LSHIFT         EX2
LCONTROL  EX3
HOME          RU
END             RD
NEXT            RR
DELETE         RL
DOWN         RD
UP                RU
SPACE          R2
K                  AR
TAB              STA
2                  EX1
NUMPAD1   L1
NUMPAD7   L1
NUMPAD8   Y
NUMPAD2   A
NUMPAD6   B
NUMPAD0   EX2
NUMPAD0   EX3
NUMPAD3   R1
NUMPAD9   R1
NUMPAD5   EX1
NUMPAD4   X

**Comment by VFansss** [comment]
Sorry for the shitty response time. I swear I'm doing my best...

> 

I can't try it myself right now, but is a lot different from [THIS](https://github.com/VFansss/mgs2-v-s-fix/issues/71)?

**Comment by mben67** [comment]
maybe, my keyboard layout is taking the actions from the r1, L1, r2, L2, square,cross, triangle, circle and puting those in my numeric keypad. to easy have access with the right hand and w,s,d,a to move the character with the left hand.

**Comment by VFansss** [comment]
With the new version of the fix, I made it easier to install an external keyboard layout.

I didn't included directly inside the fix (I can't) but should be much better now.

[I've updated the Wiki](https://github.com/VFansss/mgs2-v-s-fix/wiki/Controllers-&-Actions#playing-with-keyboardmouse) with the download link,the instructions, a brief description and a brief description of the keys.

I'm closing here, but you can always reopen the issue if there are update on topic.

Thanks again for everything 👍
