### ISSUE TITLE
"C:\WINDOWS\SYSTEM32\d3dx9_43.dll is either not designed to run on Windows or it contains an error

### ISSUE THREAD

**Issue by TheBloodEagle27** [VFansss/mgs2-v-s-fix#110]
This message comes up everytime I press Start. I did everything correctly, from game installation, to fix installation, even searched for a new .dll and nothing. Anyone else got this error as well? I read this could be a bad directx install, however, when I try to install a directx runtime it says I've got a newer version already installed and there's no need to install anything. I tried then installing an older 2010 runtime and it gave me the same error during the installation, except this time with a different .dll (xactengine2.dll instead of d3dx9_43.dll). Funny thing is the vanilla game works perfectly without the fix...

- OS: win10 x64 with latest updates as of feb 27th 2020
- GPU: RX 590 8G
- Debug:
08.50.14.887 -> [!][!][!][!][!][!][!][!][!][!][!][!]
08.50.14.888 -> [!]
08.50.14.888 -> [!] Fix started at 27/02/2020 23:50:14 (UCT)
08.50.14.888 -> [!] Fix internal version: 190331
08.50.14.889 -> [!] V's Fix has admin rights
08.50.14.890 -> [RETRIEVE LAST.LOG] last.log not found
08.50.14.890 -> [PRINT LAST.LOG] No last.log file found. Game has never started!
08.50.14.896 -> [!] forbidStart is false. Starting winform
08.50.16.008 -> [FATALERROR CHECKING] Checking for fatal errors...
08.50.16.009 -> [RETRIEVE LAST.LOG] last.log not found
08.50.16.009 -> [FATALERROR CHECKING] Check has returned this code: NoneDetected
08.50.16.010 -> [+] Form1 constructor has done. Waiting user input.
08.50.17.262 -> [+] Exit button pressed

![image](https://user-images.githubusercontent.com/18484077/75495980-abc8f480-599e-11ea-84c6-aa4221abb17f.png)

Update: So... I randomly tried deleting some files on the game's directory and after I deleted d3d8.dll and d3d9.dll the game suddenly starts... Though I'm prety sure I shouldn't have to fiddle with these .dlls to make it work.

**Comment by VFansss** [comment]
Hi,

the log you sent me is useless.

Read carefully [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#how-to-correctly-use-it) section of the guide, and send it again.

Also the files have you deleted are used by the widescreen fix and/or anti-aliasing, so probably there's some incompatibility with them...

**Comment by VFansss** [comment]
I suspect that this issues could be related to [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix)

We will never know, because I don't have the debug log.
