### ISSUE TITLE
Game dont see savegames after upgraiding fix version

### ISSUE THREAD

**Issue by Redsent** [VFansss/mgs2-v-s-fix#112]
I upgrade fix FIX to latest ver. (my old ver. was from 2018) I start FIx, run throe options, click SAVE. My save game files has migrated to new location as promised. I start game and game cant find any save games. Its empty.

I tried to copy savegame files from "new" location to "old", and then start game using game .exe and savegames work.

If i start game using FIX, its all ower again.

what did i done wrong?

**Comment by VFansss** [comment]
Ok, this doesn't seem fantastic.

> My save game files has migrated to new location as promised.

If this message appeared within the fix, meaning that is has detected some savegames inside the old location, and has at least tried to move them inside the new location.

Just to be sure: the new location is inside 'MyGames' inside 'MyDocument', and should resemble this:

![immagine](https://user-images.githubusercontent.com/15073502/76739327-56496180-676c-11ea-9d4d-2cf834521131.png)

> I tried to copy savegame files from "new" location to "old", and then start game using game .exe and savegames work.

So you are telling me that:

* If you start the game from the fix: the game doesn't read your savegames

* If you start the game double clicking the .exe : all works correctly

Am I right?

In that case, I think I've found the culprit. The solution on my end isn't easy, so I don't think there's a fast solution for that.

Albeit [you didn't send me the log like I've asked](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) I'm pretty sure you installed the game inside 'Program Files'. 

A workaround probably would be to reinstall the game inside another location that isn't 'Program Files'.

If you can, you can try to delete all files inside this directory:
C:\Users\[YOUR WINDOWS USER NAME]\AppData\Local\VirtualStore\Program Files (x86)\MetalGearSolid2 Substance\bin

If this doesn't work, I think I have to think something on how to solve this for once...

**Comment by Redsent** [comment]
> If this message appeared within the fix, meaning that is has detected some savegames inside the old location, and has at least tried to move them inside the new 
location.

Yes, i received that message, and my save game files moved to \My games  folder and dissapeared from its original location.

> I'm pretty sure you installed the game inside 'Program Files'.

No. Game installed inside like D:\games\MGS2

> So you are telling me that:

> If you start the game from the fix: the game doesn't read your savegames

> If you start the game double clicking the .exe : all works correctly

I'll try to clear this part later, then i got home.

**Comment by VFansss** [comment]
> No. Game installed inside like D:\games\MGS2

Uhm.

> I'll try to clear this part later, then i got home.

Don't forget to check the VirtualFolder I've wrote above.

Is important.

(I've slightly edited that part).

**Comment by Redsent** [comment]
I recorded video. Hope it helps.

https://youtu.be/dIPSmRPyt_c

>  you didn't send me the log like I've asked 

I tried both ways and not succeed. MGS2_VFix_debug.txt do not appear on my desktop

> Don't forget to check the VirtualFolder I've wrote above.
> Is important.

Here

![Desktop Screenshot112020 03 16 - 18 21 04 64](https://user-images.githubusercontent.com/62213075/76779653-c384e300-67bc-11ea-984e-2815b6095a1f.png)

**Comment by Redsent** [comment]
I`ve solve the problem.

long story short, i mess up.



Back in 2018 for some reason ive had 2 copies of game on my PC. One properly installed and the other gust a copy of this installed game. So seems i played back then (and have save games) "copy". Now then i tried to update FIX, i patch "Copy" and save games gone broken.



Now, then i discover multiple game copies shenanigans, I applied new FIX to "installed" game and everything working as intended.

Sorry for false bug report, and misleading. I hope you are OK out there.
