### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'D:\Games\Metal Gear Solid 2\bin\mgs2_sse.exe' is denied.

### ISSUE THREAD

**Issue by fantaandwock** [VFansss/mgs2-v-s-fix#113]
**Describe the bug**

**Have you read the manual?**

Yes, I've already read:

* [Installation guide of game and V's Fix](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing) 
* [Troubleshooting page for common issues](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#common-problems--common-solutions)
* [Lot of issues already opened/solved](https://github.com/VFansss/mgs2-v-s-fix/issues?utf8=%E2%9C%93&q=)

**Screenshots**

(You can add any screenshot simply doing STAMP+Paste in the textbox, or simply include .jpg or PNGs directly dragging and dropping on the textbox)

**Information on your machine**
- OS: [e.g. Windows 10, 7, Linux, ecc]
- You VGA Model, and if the PC is a laptop
- The V's Fix debug file. You can learn how to create it [HERE](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode). Is **VERY** important! **VERY,VERY important!**

**Additional description and extra useful things**
[MGS2_VFix_debug.txt](https://github
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/4365581/MGS2_VFix_debug.txt)
.com/VFansss/mgs2-v-s-fix/files/4365580/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
[I've answered with the solution on another Issue. Try it out and report me if its working](https://github.com/VFansss/mgs2-v-s-fix/issues/97#issuecomment-526804887)

**Comment by fantaandwock** [comment]
> 
> 
> [I've answered with the solution on another Issue. Try it out and report me if its working](https://github.com/VFansss/mgs2-v-s-fix/issues/97#issuecomment-526804887)

thanks alot for the info hopefully it works  :)

**Comment by VFansss** [comment]
I'm sure that following what I wrote has solved the issue.
