### ISSUE TITLE
Stuck in KL connecting bridge

### ISSUE THREAD

**Issue by Agateophobia** [VFansss/mgs2-v-s-fix#114]
So the problem probably isn't a fix problem, but I can't find anything about it in interwebs.
After defeating Harrier and getting to KL connecting bridge I can't progress further, every time I try to jump over gap in bridge Raiden just grabs the ledge.

**Comment by Ghaleon4** [comment]
Hey; you definitely have to jump that gap, and it has to be almost pixel perfect.  Right at the edge, and at just the right angle.  Hope you either made it already or hadn't given up.  : )

**Comment by Agateophobia** [comment]
Well, tried everything, probably tried to jump over gap for three hours, so I just gave up. I'm probably gonna try to cheat it oof

**Comment by VFansss** [comment]
Probably is something gamepad related? In the last version I've slightly tuned the gamepad sensibility, so maybe this will be solved.

Or is simply because is a shitty game design choice?

This is one of those issues that falls under the category "only God knows".
