### ISSUE TITLE
System.UnauthorizedAccessException (again)

### ISSUE THREAD

**Issue by andpl125** [VFansss/mgs2-v-s-fix#116]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/4593554/MGS2_VFix_debug.txt)
I started the V's Fix using 'Admin rights', still nothing.

**Comment by VFansss** [comment]
Hi!

Try what I wrote [HERE](https://github.com/VFansss/mgs2-v-s-fix/issues/97#issuecomment-526804887) on another issues!

**Comment by andpl125** [comment]
Thanks for the quick reply. I'll try reinstalling the game,

**Comment by andpl125** [comment]
Wow, now it works like a charm! Thank you man, you're a saint

**Comment by VFansss** [comment]
Ok, now this issue is mentioned and explained in the wiki.

I can't propertly address it, but isn't too hard to avoid it.

It's the I can do right now.
