### ISSUE TITLE
Issue with savegames access

### ISSUE THREAD

**Issue by Audioslaver** [VFansss/mgs2-v-s-fix#117]
Hello, I'm getting a saved games issue when I try to load a game.
Game is installed in D:\Jeux\MetalGearSolid2\savedata
I see that the installer created a copy in D:\Users\"My_name"\Documents\My Games\METAL GEAR SOLID 2 SUBSTANCE
(like it's supposed to do since the last update).

I manage to start the game and save. 
BUT when I close the game, and relanch it afrter : I can't load a saved game : "no data file".
Checking : both savedata folders contain the same folders and files.

If I empty D:\Users\"My_name"\Documents\My Games\METAL GEAR SOLID 2 SUBSTANCE : I am able to see all the saved games.

I tried :
1- let D:\Jeux\MetalGearSolid2\savedata and empty the original folder intact : impossible to see the saved files
2- If I empty D:\Users\"My_name"\Documents\My Games\METAL GEAR SOLID 2 SUBSTANCE and let the original folder intact : I can see and launch saved games

**Comment by VFansss** [comment]
Hi!

I know that's annoying, but can you try to do the same things that has solved [THIS](https://github.com/VFansss/mgs2-v-s-fix/issues/116) issue?
