### ISSUE TITLE
Settings menu doesn't work

### ISSUE THREAD

**Issue by Deathsparks** [VFansss/mgs2-v-s-fix#12]
Fix installed successfully but I keep getting this error that says "Unhandled Exception" everytime I try to select the settings. I'm on a ASUS laptop with a GTX 960m and I'm completely lost.

**Comment by VFansss** [comment]
Wow, it's my fault for sure :(

[Activate the debug mode](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) and send/post me the file you found in your desktop!

Also, try to delete configuration_file.ini in your game folder!

**Comment by VFansss** [comment]
Should be solved in the last build
