### ISSUE TITLE
Game can't save in "Documents" folder

### ISSUE THREAD

**Issue by NikitaKitoslav** [VFansss/mgs2-v-s-fix#120]
Hello!
When saving in game, its doesn't create a folder in \Documents\My Games\ and don't create any save files

Log file:
https://drive.google.com/file/d/18kBEmotiQrzps72KZOvxyv_fjD50-Pfc/view?usp=sharing

**Comment by VFansss** [comment]
Hi!

Sorry for the late reply (I swear that I'm truly physical tired lately)

I can't access your log (is protected, thus I should ask for access)!

[Did you done what I wrote here in the guide?](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix)

Is a thing that I wrote recently, and is very important!
