### ISSUE TITLE
Some operation has been blocked by operation system

### ISSUE THREAD

**Issue by christofer41** [VFansss/mgs2-v-s-fix#122]
Hello!

When I try to install the Fix I get the message saying that some operations has been blocked by operating system.
I have given Admin rights, installed in another folder, and enabled read/write permissions on everything except Special permissions.

Windows 10 64 bit
16gb Ram
AMD Radeon RX 5700
AMD Ryzen 7 3700X 8-Core

![Untitled](https://user-images.githubusercontent.com/56994541/83972555-17e1bf80-a8e1-11ea-884e-d1cfd02a739b.png)

[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/4742299/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
Hi there.

[Did you done what I wrote here?](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix)

**Comment by christofer41** [comment]
Hi!
It was already unchecked when I downloaded it ^^

**Comment by VFansss** [comment]
Then I need the debug log.

[Check how to get it HERE](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode).

**Comment by christofer41** [comment]
It should be included above :)

**Comment by VFansss** [comment]
I'm an idiot.

You are right.

Seems that, albeit everything, Win is blocking the extraction of the game executable.

Can you please do a test?

* Unistall the game (sorry 😢 )
* Reinstall the game to ANOTHER LOCATION (important)
* Download the fix again.
* [Unlock security on the file](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix)
* Simply install it and redo everything again.

I know that is annoying, but is very important.

I tought that disabling that flag could be enough to overcome this issue, but...
