### ISSUE TITLE
Failed access to game folder 

### ISSUE THREAD

**Issue by Mazen767** [VFansss/mgs2-v-s-fix#123]
I can't open the game it's say failed access to the game folder I true off the antivirus and the same problem I reinstalled the fix and the game from another website the same problem + even without the fix when I open the game it's say pls insert game name disk I don't know what's going on 

**Screenshots**

https://drive.google.com/file/d/1S49ci1LyxL54hq-3Rm2Eluko9rJgpMgJ/view?usp=drivesdk

**Information on your machine**

- OS:  Windows 10
8 gig ram 
Intel core I 7 3.10 GHz
Intel Graphic card 4400
Yes it's a laptop

And thank you for this amazing work I appreciate that

**Comment by VFansss** [comment]
Can I ask why you closed the issue?

Did you solved? How?

**Comment by Mazen767** [comment]
I solved the problem I really don't know how I just download the game and
run the fix and the game run I guess I don't setup the whole game or the
download failed in some point but the problem is from me not the fix anyway
thanks for your reply and thanks for this amazing fix
