### ISSUE TITLE
CreateDXGIFactory 2 could not be located

### ISSUE THREAD

**Issue by warmach1ne** [VFansss/mgs2-v-s-fix#13]
Thank you so much for the fix!

the procedure entry point createDXGIFactory2 could not be located in the dynamic link library c:\Windows\SYSTEM\d3d11.dll

I am guessing this is Sweetfx trying to use directx11. What should I do remove the 

Delete: dxgi.dll (or rename to dxgi.dll.bak)
Delete: dxgi.fx (or rename to dxgi.fx.bak)

**Comment by VFansss** [comment]
I didn't understand : so if you delete these 2 files it works?

**Comment by warmach1ne** [comment]
I'm running the fix on windows 10 and the fix works but after showing the error multiple times.

After deleting those two, the error does not show up anymore.

**Comment by VFansss** [comment]
Uhm, I don't think these files are needed in our case...

I will send some email to SweetFX regarding their use and maybe in the next release I will delete them.

Thanks for reporting me, through!

I hope all others things are working good!
Have fun!

**Comment by warmach1ne** [comment]
Thank you so much for this fix.

p.s. I am a fan of this game for a long long time although phantom pain was a disappointment, I'm trying to play through past Hideo Kojima's masterpieces.

**Comment by VFansss** [comment]
Solved in the last build
