### ISSUE TITLE
Some operation has been blocked by operating system

### ISSUE THREAD

**Issue by Speshimen75** [VFansss/mgs2-v-s-fix#134]
Hey I really like MGS2 and it came to my attention that gog was selling it, so I went there and bought a copy. People in the comment section recommended me to get this patch (after reading the change log I'm convinced its the right decision).

Unfortuantly the V's fix wont even start up for me.

I did checked the box you  specifically told te to check and hit apply.
However since the game.exe file is called ''mgs2_sse'' instead of ''MGS2SSetup'' on the gog version. I renamed the V fix 1.8 to ''mgs2_sse'' and then overwritted the standard .exe in the /bin folder.

I've tried uninstall and reinstall in 3 different directories (non of them we're inside a program files folder)
I've tried to disable my UAC and then launch.

Maybe you have already answered this question and im blind, but im posting this just to be sure. 
So my apologies if there was a fix already available for this issue.

My debug file is attached to my post.

Thank you for your time in advance 
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/5292923/MGS2_VFix_debug.txt)

**Comment by Speshimen75** [comment]
EDIT:

The line in the debug text file: 04.17.46.914 -> System.IO.IOException: Kan geen toegang krijgen tot het bestand C:\Metal Gear Solid 2 Substance\bin\mgs2_sse.exe omdat het wordt gebruikt door een ander proces.

Translates rougly to English as: 
04.17.46.914 -> System.IO.IOException: Can't get access to the file C:\Metal Gear Solid 2 Substance\bin\mgs2_sse.exe because it is being used by another process.

**Comment by VFansss** [comment]
Hi!

> However since the game.exe file is called ''mgs2_sse'' instead of ''MGS2SSetup'' on the gog version. I renamed the V fix 1.8 to ''mgs2_sse'' and then overwritted the standard .exe in the /bin folder.

😨 

Don't rename anything.

Simply install the game from GOG, copy and paste the fix inside the game folder and...you are done.

Don't rename anything, don't move anything!

**Comment by Speshimen75** [comment]
Wow you are fast, thanks!

I feel like an idiot right now. 
The first time I tried that it gave me a window that I was in the wrong folder while I was sure I was in the right one. 
Reinstalled just now and just dragged the file inside the game folder and the V's fix window popped up just fine.

So I assume its fixed now. Thanks again for your fast help and work on this patch!
