### ISSUE TITLE
game crashed on startup when controller is enabled

### ISSUE THREAD

**Issue by theologoumenon** [VFansss/mgs2-v-s-fix#136]
i'm using the gog version, game crashed a few seconds after starting, turning off controller in settings works fine but i want to use my xbox controller

[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/5299013/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
The new release could have solved this.

Please retry using v1.8.1 version of the V's fix
