### ISSUE TITLE
Request to switch bumpers with triggers.

### ISSUE THREAD

**Issue by Tomasak** [VFansss/mgs2-v-s-fix#14]
Well the name says everything. Would you please add switch option to switch bumpers with triggers? It's good for xbox 360 and one gamepads as you know the aiming is more needed than switching between items so it's handy to have it on the bigger "button" (sorry for closing and reopening, thought pull request is for requests :D)

**Comment by VFansss** [comment]
Sorry for the late reply!

I always played "like the ps2", with the menu/weapon button opened with the triggers.
Implementing this would require some time, but maybe in the next version I could implement that...

For now,there's an easy way:

Go to game folder and open padbtn.ini.
Then find the line that begin with 04, 05, 0A and 0B.
You have to invert content of line 04 and 05 with content of line 0A and 0B.

For example in V's Layout you have to write this in that lines:

    04  L1
    05  R1
    0A  L2
    0B  EX3

This would do the work. 
Tell me if it's a lot better, in your opinion!

**Comment by Tomasak** [comment]
Yes, it feels more natural this way. Never understood why are aim and shoot buttons bind to R/L1 and switch weapon to R/L2 in PS2 games.

**Comment by VFansss** [comment]
Probably because aiming with triggers is a more "recent" behaviour, I think...
Back in 2001 there were still a lot of things to discover :p

**Comment by VFansss** [comment]
After 854 days, I've delivered this improvement!

I had to rewrite a lot of things, but I think it was worthy!

We can't say I don't do improvements 😛 

From the upcoming 1.8 Version, it should be in place, ready to be selected!

**Comment by DanielFrankDK** [comment]
Unfortunately, I'm having trouble inverting RT/LT with RB/LB. Whenever pressing "OFF", nothing happens. Any thoughts?

**Comment by Tomasak** [comment]
it actually changes stuff in ini and in-game, however it doesnt show change in settings screen
