### ISSUE TITLE
Failed creating Direct3DDevice8 Object (GOG Installation, Windowed mode: off) 

### ISSUE THREAD

**Issue by brianor63136** [VFansss/mgs2-v-s-fix#144]
My issue appears to be similar to the issue reported here:

https://github.com/VFansss/mgs2-v-s-fix/issues/55

I am running MGS2 on a HP Pavilion Gaming Notebook running Windows 10 with an Intel(R) HD Graphics 530 card.

Attached my most recent debug where the game successfully ran with Windowed Mode set to 'On'. Once I post this, I will add a failing state debug as well.

[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/5356646/MGS2_VFix_debug.txt)

**Comment by brianor63136** [comment]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/5356651/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
From the log I can see:

06.45.44.400 -> [D] Key: Height -> Value: 1080
06.45.44.402 -> [D] Key: Width -> Value: 19**80**

Did you sure that you monitor is that resolution?

Did you want to write 19**20**x1080 instead?

**Comment by brianor63136** [comment]
Ah, that's it. I knew it was something dumb like that. 

Thanks for your help
