### ISSUE TITLE
what file do i put the v fix in i cant get it to work

### ISSUE THREAD

**Issue by jackjev** [VFansss/mgs2-v-s-fix#148]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VFansss** [comment]
Hi there.

Please check the [Downloading & Installing](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing) wiki page.

You should find every information you need.

Unfortunatelly I didn't had the time to edit the page to include more info for the GOG release, thus the wiki page talks about the retail game version, but (generally) the steps you have to make are the same:

* Download the fix [HERE](https://github.com/VFansss/mgs2-v-s-fix/wiki#download-link-arrow_down)
* You then have a .zip file, and inside it you will find an .exe file
* Find where you have installed the game
  * Retail Version: by default in "C:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance"
  * GOG Version: Default GOG directory
* Put the .exe file inside the "bin" folder inside the game directory
  * If you have the Retail Version installed, overwrite the already existing files. Shoudn't be need for the GOG version of the game.
* Launch MGSS2Setup.exe

**Comment by jackjev** [comment]
GOG directory?

**Comment by jackjev** [comment]
This is what my files look like btw

**Comment by VFansss** [comment]
Well, now the "[Downloading & Installing](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing)" Wiki page is much more clear.

Should be enough
