### ISSUE TITLE
Missing game audio

### ISSUE THREAD

**Issue by unfussybonsai** [VFansss/mgs2-v-s-fix#15]
Thanks to this patch, the game is finally working. But I'm missing the music and voice audio. The sound effects of, for example, the main menu and codec call sound is working, but there are no voices or music. I've reinstalled the game multiple times and checked the options to see if the sound was actually on, but both didn't work. 
Is there a fix for this yet?

**Comment by VFansss** [comment]
In the main menu go to option and see if MUSIC and SE is at the max (15). Is a silly things but...

**Comment by unfussybonsai** [comment]
It's turned on. I've already checked that before.

**Comment by unfussybonsai** [comment]
Okay, I've found the solution. It's not your patch that caused the bug. Because the game works without it (except for the fact that I'm missing most of the textures, but that's not the point). I turned the sample rate of my headphones/speakers down to 24 bit, 44100 Hz (Studio Quality). Now I have music and voice audio.
