### ISSUE TITLE
invert Y in first person

### ISSUE THREAD

**Issue by splooie** [VFansss/mgs2-v-s-fix#151]
**Is your feature request related to a problem? Please describe.**
all i want in life is for there to be inverted Y axis in first person view. it makes the game unplayable.

**Describe the solution you'd like**
an option to invert y for first person view or some kind of workaround

**Describe alternatives you've considered**
i'm trying to figure out a button chord combo or mapping that would remap the y axes but only when the first person button is held?

**Additional context**
this seems like a wild oversight and i will never forgive kojima.

**Comment by VFansss** [comment]
Hi!

Before everything, I have to say it: I truly don't understand who inverts the Y axis in every game that isn't Ace Combat.

> y axes but **only** when the first person button is held?

Is probably doable somehow, albeit is far from my competence field :(

You could, obviously, invert axis of the right analog but I think you already thought that.

Let's mark this with "Help needed" and see if someone has some clever idea.

**Comment by bmn** [comment]
![image](https://user-images.githubusercontent.com/52235/104080981-9316a580-5223-11eb-8c05-922e4b5da8ba.png)

**Comment by VFansss** [comment]
❤️
