### ISSUE TITLE
PS5 Controller Compatibility

### ISSUE THREAD

**Issue by SkullDr** [VFansss/mgs2-v-s-fix#153]
I know It's too early but steam already got the Support for it and it works fine but a "direct" compatibility would be great.
Please keep in mind I understand this is NOT a priority: take all the time you need.
I just want to say that your work is amazing and I'm very grateful.
Thx

**Comment by VFansss** [comment]
I think is simply too early to do this.

Steam is supporting it, but you have to manually do your button mapping through its gamepad remapper.

The only way to support this without Steam is:

* Check if the gamepad is recognized as a Xinput (probably not)

* "" as a Dinput controller and make a dedicated button layout (just like I've done with DS4). I bet that this would work, but this would mean that I should get the controller (and this will not happen)

* See if there will be a "DS5Windows" just like we have "DS4Windows".

In every case, I don't know if and how we could support all the dualsense little hardware gimmick.

**Comment by Kanuan** [comment]
Just to comment on this, DS4Windows already has support for the DS5 controller, as well as the Dualshock 3 (when under the DsHidMini driver and in "DS4 mode") and Switch's Pro Controller and Joy con. So basically, they all already work both with the patch's XInput or DS4 mode.
