### ISSUE TITLE
Failed creating Direct3DDevice8 Object.

### ISSUE THREAD

**Issue by NOIRsteam** [VFansss/mgs2-v-s-fix#155]
**Describe the bug**

**Have you read the manual?**

Are you sure you have read these pages?

A LOT of infos can be found there, and usually it's more than enough to solve the most common problems...

* [Installation guide of game and V's Fix](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing) 
* [Troubleshooting page for common issues](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#common-problems--common-solutions)
* [Lot of issues already opened/solved](https://github.com/VFansss/mgs2-v-s-fix/issues?utf8=%E2%9C%93&q=)

**Screenshots**

(You can add any screenshot simply doing STAMP+Paste in the textbox, or simply include .jpg or PNGs directly dragging and dropping on the textbox)

**Information on your machine**
- OS: [e.g. Windows 10, 7, Linux, ecc]
- You VGA Model, and if the PC is a laptop
- The V's Fix debug file. You can learn how to create it [HERE](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode). Is **VERY** important! **VERY,VERY important!**

**Additional description and extra useful things**

**Comment by NOIRsteam** [comment]
Hello, can you help me with my issue? 
![Скриншот 21-12-2020 215801](https://user-images.githubusercontent.com/76440789/102790262-c8279900-43d7-11eb-8435-6cc9699244a7.png)
![Скриншот 21-12-2020 215820](https://user-images.githubusercontent.com/76440789/102790271-ca89f300-43d7-11eb-830b-db47cf70a944.png)
![Скриншот 21-12-2020 215835](https://user-images.githubusercontent.com/76440789/102790274-cb228980-43d7-11eb-859a-45f5cd79397d.png)
![Скриншот 21-12-2020 215853](https://user-images.githubusercontent.com/76440789/102790277-cc53b680-43d7-11eb-940f-46642fb0dd7c.png)




[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/5724965/MGS2_VFix_debug.txt)

**Comment by NOIRsteam** [comment]
I've PC on Windows 10

**Comment by VFansss** [comment]
Hi!

From the log, seems that the fix can't apply the audio fix to the game:

  ```
11.05.38.004 -> [ ] Audio not patched. Applying Audio Fix
  11.05.38.120 -> System.UnauthorizedAccessException: Отказано в доступе по пути "D:\GOG Galaxy\Games\Metal Gear Solid 2 Substance\bin\dsound.dll".
     в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
     в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
     в System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
     в mgs2_v_s_fix.Unzip.UnZippa(String fileToUnzip, Boolean OverWrite)
     в mgs2_v_s_fix.Program.Main(String[] args)
```

Did you done [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix) when you downloaded the fix?

**Comment by NOIRsteam** [comment]
I haven't this option.
![Скриншот 21-12-2020 232137](https://user-images.githubusercontent.com/76440789/102798237-653bff00-43e3-11eb-85ca-c47e8fc5e623.png)
Sorry it in Russian

**Comment by NOIRsteam** [comment]
Do I need to download WinRAR?

**Comment by VFansss** [comment]
> I haven't this option.

Uhm...

> Do I need to download WinRAR?

No, don't worry.

Well, I guess we can try to install manually the audio fix, if the fix can't do that itself.

* Download the audio fix from [HERE](https://github.com/VFansss/mgs2-v-s-fix/raw/master/mgs2%20v's%20fix/Resources/2_audio_fix.zip)
* Extract its content inside the "bin" game folder (the same where you basically pasted the fix). Overwrite, if is asking to.
* Inside the "bin" folder, create a file called "_audio_fix_applied.sss" (without quotes)
  * **BEWARE THE ".sss" FILE EXTENSION**

**Comment by NOIRsteam** [comment]
![Скриншот 22-12-2020 002312](https://user-images.githubusercontent.com/76440789/102804262-19da1e80-43ec-11eb-9cdc-a8236a7dbf55.png)
![Скриншот 22-12-2020 002230](https://user-images.githubusercontent.com/76440789/102804273-1cd50f00-43ec-11eb-99a7-221690a87171.png)

**Comment by VFansss** [comment]
Can you please perform this:

No, don't worry.

Well, I guess we can try to install manually the audio fix, if the fix can't do that itself.

    * Download the audio fix from HERE
    * Extract its content inside the "bin" game folder (the same where you basically pasted the fix). Overwrite, if is asking to.
    * Inside the "bin" folder, create a file called "_audio_fix_applied.sss" (without quotes)
       BEWARE THE ".sss" FILE EXTENSION
    * Proceed like usual (Open the fix, press "OPTION" then "SAVE")

**Comment by NOIRsteam** [comment]
Program create new _audio_fix_applied.sss by it self (that's above)
![Скриншот 26-12-2020 025239](https://user-images.githubusercontent.com/76440789/103141339-90955580-4725-11eb-8f39-67679c839140.png)

**Comment by dwde123** [comment]
I also have this problem, i've tried the sound fix and nothing has changed. Any other solutions?

**Comment by VFansss** [comment]
With v1.8.1, the GOG Galaxy version of the game shoudn't have this issue anymore.

**Please download and install correctly the latest version**

If it return in some form, I would like to work with new logs and the new version of the fix.

So I'm closing this, for now.
