### ISSUE TITLE
Water Texture issue  

### ISSUE THREAD

**Issue by MGS290** [VFansss/mgs2-v-s-fix#156]
When I start playing mgs2 substance on my laptop, I have an issue with water texture graphics where the water does not appear, is there any fix need to be applied or a workaround.
![MGS2 PC Water Texture](https://user-images.githubusercontent.com/76570834/103106339-a4698a80-4645-11eb-94d2-fb30408813b2.jpg)

**Have you read the manual?**
Yes I read the manual.

Are you sure you have read these pages?
Yes.

A LOT of infos can be found there, and usually it's more than enough to solve the most common problems...

* [Installation guide of game and V's Fix](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing) 
* [Troubleshooting page for common issues](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#common-problems--common-solutions)
* [Lot of issues already opened/solved](https://github.com/VFansss/mgs2-v-s-fix/issues?utf8=%E2%9C%93&q=)

**Screenshots**
![MGS2 PC Water Texture](https://user-images.githubusercontent.com/76570834/103106343-b2b7a680-4645-11eb-93a3-1af449ec17a8.jpg)

(You can add any screenshot simply doing STAMP+Paste in the textbox, or simply include .jpg or PNGs directly dragging and dropping on the textbox)
![MGS2 PC Water Texture](https://user-images.githubusercontent.com/76570834/103106350-c531e000-4645-11eb-9ac4-92ae5bbf0148.jpg)

**Information on your machine**
- OS: Windows 8.1
- You VGA Model, and if the PC is a laptop: Nvidia GTX 765M, MSI Gaming Laptop GS 70 Stealth 
- The V's Fix debug file. You can learn how to create it [HERE](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode). Is **VERY** important! **VERY, VERY important!**

I tried the same steps mentioned in the above link but there is no debug saved, could you please illustrate more and help on this. Is it a normal text file with the name debug.sss that i have to create in the GAME DIRECTORY/bin folder

**Additional description and extra useful things**

**Comment by VFansss** [comment]
Did you read [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Settings-Menu#graphical-adapter) part of the wiki?

You need to tell windows what graphical adapter are you using
