### ISSUE TITLE
Cannot access 'mgs2_sse.exe' because it is being used by another process.

### ISSUE THREAD

**Issue by Nowhereman119** [VFansss/mgs2-v-s-fix#164]
Hello,

I have tried everything I could to get the game to start but I am not having any luck, the game closes immediately as I press start. Here is the txt file that appeared on my desktop after running the debugger.
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/6244817/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
To produce an useful log, you have to press "SETTINGS" and then "SAVE", as I've explained [HERE](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#how-to-correctly-use-it)

Send me another log after you followed the guide I've linked, so I can investigate if there's some issue...

**Comment by Nowhereman119** [comment]
Thanks for the reply, sorry about that. I believe this log is correct.

[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/6249737/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
The logs say:

> Message:The process cannot access the file 'F:\GOG\Metal Gear Solid 2 Substance\bin\mgs2_sse.exe' because it is being used by another process.

Seems that the mgs2_sse.exe is opened when you press the "SAVE" button.

Please reboot your pc and be 100% sure that the game is closed when you configure the game.

**Comment by Nowhereman119** [comment]
I am a little confused, isn't mgs2_sse.exe your fix where I am changing these settings from? I have the game on GOG and the mgs2_sse.exe file in the bin folder of the game. Whenever I run the game on GOG, your fix automatically starts up and that is where I am given the options of start, settings, and exit. How can I have mgs2_sse.exe closed at the same time I am changing the settings and clicking save?

**Comment by VFansss** [comment]
> isn't mgs2_sse.exe your fix where I am changing these settings from?

ABSOLUTELY NOT.

"mgs2_sse.exe" is the main game executable.

If you download my fix .zip file, you will see that my fix exe is called "MGS2SSetup.exe", and is intented to replace the original game setupper.

Did you renamed that file to something else?

>  Whenever I run the game on GOG, your fix automatically starts up and that is where I am given the options of start, settings, and exit.

Yes, and this happen because GOG is trying to open the original game setupper, that is replaced by mine.

> How can I have mgs2_sse.exe closed at the same time I am changing the settings and clicking save?

Because you should use my fix (MGS2SSetup.exe) to setup the game .exe (mgs2_sse.exe) that obviously can't be running in the meanwhile.

[The installing guide should be very clear on how to install it](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#how-to-apply-the-fix)

**Comment by Nowhereman119** [comment]
Ok I believe I understand what I did wrong, it looks like I replaced the executable of the game as opposed to the game setup with your fix, I am going to reinstall the game and try again. Thank you for your help and for clearing that up.

**Comment by Nowhereman119** [comment]
If the game set up file on GOG is not named "MGS2SSetup.exe" (I don't believe it was when I was first setting this up by I may be wrong), I would just need to change your fix to have the same file name, and then move that into the bin folder of the game to replace it, correct?

**Comment by VFansss** [comment]
>  I would just need to change your fix to have the same file name, and then move that into the bin folder of the game to replace it, correct?

No, you don't need to overwrite anything, if not required. Just copy the fix and run it, don't rename anything.

[Please follow the installation guide carefully](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#how-to-apply-the-fix)
