### ISSUE TITLE
No vibration on ps3 gamepad

### ISSUE THREAD

**Issue by Michele090** [VFansss/mgs2-v-s-fix#166]
Hi,
I am using a ps3 gamepad that has vibration, the vibration works with all my games but with Metal gear solid 2 doesn't work. Why?

**Comment by w1lddog2** [comment]
Is it an original one???  Because fake PS3 gamepads are just a hit or miss..  Everything may work great or BT may not work,etc.

Sometimes the fake gamepads work like  a charm on an original PS3 console, yet they will have issue on PC.

**Comment by Michele090** [comment]
My gamepad is:
https://www.speedlink.com/en/STRIKE-NX-Gamepad-for-PC-black/SL-650000-BK-01

The vibration of this joypad works with ALL MY GAMES, even old games like Prince of Persia Forgotten sands and Virtua tennis 2 (it is necessary x360ce_x86 emulator for vibration).
**The problem is this fix: the mgs2-v-s-fix blocks the x360ce-x86 emulator**

**Comment by w1lddog2** [comment]
But that is not a ps3 gamepad,  it's a third party gamepad that works on a PS3.   It even has XInput
You should not need any extra software to play MGS2, because this fix supports XInput.  In fact you should not need  x360ce on any game that supports XInput.

**Comment by Michele090** [comment]
In fact my gamepad works without x360ce, but for the vibration in old games is necessary x360ce, but this fix blocks x360ce, I don't why......the problem is this fix, it is a bug.

**Comment by w1lddog2** [comment]
OK, but listen:
This Patch doesn't need x360ce, you should not use x360ce with this patch.  Don't run x360ce while using mgs2-v-s-fix and the vibration will work.

**Comment by Michele090** [comment]
YOU ARE RIGHT !!!!!! If you don't touch the controls tab of the fix, the VIBRATION WORKS !!!!! I am very happy and thanks a lot for this amazing Patch !!!!!!!!!!!!!!!!!!!!!
