### ISSUE TITLE
Doubt - High CPU usage

### ISSUE THREAD

**Issue by SilentMRG** [VFansss/mgs2-v-s-fix#171]
Hi... :-)

I have the GOG version and I have a 2.67 GHz I5 processor. I know that there are better processors than this one. What I can't understand is why MGS2 uses so much CPU?!
 
I have already run much heavier games and the CPU usage is no more than 30%. Only with the MGS2 the CPU usage is around 50%, 60% and in many parts it reaches 80% and even 98%!!! This is insane for such an old game.

On the other hand, the game does not suffer drops in FPS, does not crash, in short, everything in the game works perfectly (except for the bugs that Konami/GOG did not fix). What I don't understand is this high CPU usage. Does anyone know why?

Remembering that this only happens with MGS2 with or without the VFansss patch.

Perhaps... an optimization in VFansss is welcome to minimize this high CPU usage. I leave that suggestion! 

For if we expect any correction from Konami or GOG, we die of old age. XD

Has anyone else experienced this "problem"?

Thank you so much for reading and for your attention! =D

**Comment by VFansss** [comment]
I thought that I replied to this topic. Instead probably I only thought to do that but I forgot.

Sorry for the late reply.

> I have already run much heavier games and the CPU usage is no more than 30%. Only with the MGS2 the CPU usage is around 50%, 60% and in many parts it reaches 80% and even 98%!!! This is insane for such an old game.

"Heavier" is a weird concept.

MGS2 is a very old game, and was built in an epoch where single core CPU was the norm.

Probably more recent games knows how to better use multiple cores and have better performances overall.

But for such as old game, the only things that matter is single core performance and ghz, that in your case are probably less advanced...

> Perhaps... an optimization in VFansss is welcome to minimize this high CPU usage. I leave that suggestion!

Honestly this can be done probably, but is truly out of scope of what I'm able to do, and probably this woudn't be done even on an official release, let alone optimizing such an old and niche game.

**Comment by SilentMRG** [comment]
Hi...

No problem about the delay in responding... It happens!

I'm from Brazil and here the concept "heavier" is used to describe games that demand a lot of computer resources, that is, it is a popular concept said among my people. And I have a bad habit of forgetting that there are people from other countries on the internet, hehehehe. XD

Ahh... there it is! That's what I suspected! MGS2 uses only one CPU core and this explains the high processing consumption.

I understand your point. No problems either. After all, you are already doing a lot for the entire community, because, what you do, neither GOG nor Konami ever thought of doing it.

I am grateful for your work anyway!

Thank you very much!


Note: I didn't even remember this topic anymore! Hahaha... XD

**Comment by SilentMRG** [comment]
Off-topic conversation...

Have you heard about the Classic REbirth project?

No?!

Well, here we go: https://appleofeden.de-doc.com/

This content exemplifies: https://youtube.com/c/geminimewtwo

This is a high quality project just like yours! In my humble opinion, this project makes the classic games definitive versions, so good are the added features and the implemented fixes.

It's that "Love Letter" given to the good old days! \o/

I leave this tip! =D

**Comment by VFansss** [comment]
I didn't know about that!

For sure my favourite "restoration" project is the [Silent Hill 2 Enhanced Edition](http://www.enhanced.townofsilenthill.com/SH2/).

These guys have done an amazing work (and also helped me on some things for this fix).

Unfortunately my work is much less refined that the above ones, but its a good try :)

**Comment by SilentMRG** [comment]
You can be sure that your work is very refined too! =)

I am so grateful for everything you are doing. All of you are rescuing/saving classics that developer companies don't give a shit about. VFansss/mgs2-v-s-fix, SH 2: Enhanced Edition and Classic REbirth, you are pure programming legends! =D Again, my thanks! \o/

Silent Hill 2: Enhanced Edition is a magnificent project! I met him a short time before the re-release of Silent Hill 4: The Room on GOG. By the way, I don't understand why GOG has re-released SH 4 instead of SH 2. The second installment of the series is an absolute classic! And SH 4 is a waste of time.

I met the Classic REbirth project at the end of last month and really enjoyed replaying RE 1, 2 and 3 + Dino Crisis genuinely on PC, bug free and with Xbox 360 gamepad support plus many other improvements. Before I could only play via emulation on ePSXe, hehe.

Now I'm looking forward to Dino Crisis 2 (future release Classic REbirth). In my humble opinion, this is the best game of the games Capcom has released in the PS1 era, and genuinely replaying it on PC, it will be nostalgia for "over 8000!" This is a reference to a "not very well known" Japanese drawing. :-D

And it looks like the developer of Classic REbirth is Italian too. I am happy to see these restorations being carried out by Italians, as I am of Italian descent, hehe, but I have no talent for that: restoration/programming. So I remain in the field of appreciation and dissemination!

Note: Dammit... I talked a lot! Hahaha... XD

Thanks man... Thanks so much for saving my fun!

**Comment by SilentMRG** [comment]
Me again! =D

Do you know the OpenBOR engine?

This guy F-GAMES (Brazilian) has done an amazing job with almost all the content on Streets of Rage.

Meet Streets of Rage 2X: https://youtube.com/channel/UCP75iA2wLACP1p-3r2TB6Gg

Other channels with similar content:

https://youtube.com/c/ZVitor

https://youtube.com/c/DouglasBaldan78

All are from Brazil! And they are at the forefront of programming for OpenBOR and MUGEN (another engine focused on 1vs1 fighting games).

Here: http://www.chronocrash.com/forum/index.php is the meeting place for the great programmers and supporters of numerous projects based on the OpenBOR and MUGEN engine.

Ahh, this is SEGA's famous "ban": https://sorr.forumotion.net/t838-new-streets-of-rage-remake-v5-2-download-and-info#15816

It received a major update last year.

Have fun my friend!

And one more time...

Thank you... \o/
