### ISSUE TITLE
Controller layout is all over the place

### ISSUE THREAD

**Issue by MooseZM** [VFansss/mgs2-v-s-fix#176]
Controls are all over the place, for starters, the RB and LB are switched with start and select, idk where X went so i can't shoot the guns, Y does nothing, The triggers do nothing as well. I tried all the layouts (even steam's) but no dice. I'm using a random controller but it's recognized as an xbox controller (even by steam), i saw that it's not a problem in the manual. I'm also using the GOG version if it's relevant

**Comment by SammyCola** [comment]
I would check to see if your random controller is using the correct layout in the Game Controllers tool in Windows (can be searched in the Start Menu under "Set up USB Game Controllers".

This is what my Xinput controller maps to, and it maps 1:1 with the games original controls.
![Layout](https://user-images.githubusercontent.com/19739806/133509992-82e1c5cf-e088-4714-8bec-a3619f0a02ca.png)

**Comment by MooseZM** [comment]
only the first few are the same, then i get different buttons, also worth mentioning that i have 15 buttons instead of 10 (triggers are buttons to me, not an axis like yours), so maybe that's the issue. This is the only game i have this problem on though. It works fine on all steam games (and if i add some non steam games as a non steam game the controller works fine as well). I might try out the x360ce again
![image](https://user-images.githubusercontent.com/85148899/133557586-dbe66145-8da6-423f-aeef-ac368978bc04.png)

**Comment by MooseZM** [comment]
I managed to fix it. PC was recognizing the controller as 2 controller for whatever reason, I disabled one of them and tried x360ce again and it worked fine.

**Comment by MooseZM** [comment]
I managed to fix it. PC was recognizing the controller as 2 controller for whatever reason, I disabled one of them and tried x360ce again and it worked fine.
