### ISSUE TITLE
Xbox Controllers Right Stick pulling to one side on Map and Elevator Floor selecting

### ISSUE THREAD

**Issue by Buffdaddy123** [VFansss/mgs2-v-s-fix#181]
Using an Xbox 360 Controller Wireless, or a Xbox one Controller with Wireless Adapter game is fine except when viewing Map or Using Elevator and floor selecting the right stick seems to be pulled up..

So map is pulled down when viewing, and in Elevator when selecting a floor you cannot see it , the view is just pulled upwards.

Using a PS4 Controller is completely fine and no issue.

Running game without Vs Fix Controllers are all fine.. But obviously losing Vs enhancements.

Any ideas?

**Comment by VFansss** [comment]
Hi there.

Can I know what you did to solve the issue?

**Comment by Buffdaddy123** [comment]
Hi, well it was a strange one, I was using my Xbox controller with my Wireless Xbox adaptor and all was good,

Decided to use try the Dual Shock 4 using the PS4 Wireless adaptor and all also worked perfectly,

Went back to using the xbox One and 360 Controllers and issues started,

Finally found that leaving the PS4 Wireless adaptor connected to a USB port was causing the problem, Removed it while in the game with any xbox controllers and the issue stops immediately, Tried in other USB ports and always same issue..

Very strange, but hope this info is useful, many thanks for this fix.

Can i ask you 1 question, If im using GOG MGS2 and use your fix, do i still need to enable the AF and AI settings in the Direct X of the SOF2 game or is this already enabled by the patch?

Thx.

Also forgot to add...If i ran the game from standard exe and NOT using your fix.. Everything worked as it should without needing to remove the PS4 Wireless Adaptor.
