### ISSUE TITLE
Add binary to releases

### ISSUE THREAD

**Issue by Keith94** [VFansss/mgs2-v-s-fix#2]
Can you please add v1.01 binary to the releases page, and link to it from the readme. This is common practice for similar projects like these. Thanks :)

**Comment by VFansss** [comment]
Onestly I didn't used it only cause I wanted to retain a download counter.

I didn't know that Github has one, for "Release" function.

I will update it when I upload the next version (1.02) with Anti-Aliasing and some fixes!
Thanks for the tip!

**Comment by Keith94** [comment]
Cool, looking forward to it. :)

What kind of AA settings will you be adding? I'm assuming the game supports MSAA since it's an older title.

**Comment by VFansss** [comment]
I've searched for a built-in solution. Unfortunatelly I can't crawl deep into the game to trying to inject AA myself (I would not know how to do, also it's VERY time consuming). I'm using SweetFX with SMAA. It's heavier than FXAA but has better result. And it's an old game, so I don't think it's very important. It has MIT licence, so I can distribute it into my fix without having to send tons of mail for credits.

It's kinda hard to conciliate it with WS fix and XInput Plus cause all these 3 libraries rely on a modified version of dxinput8.dll. Also internal logic of the fix must be polished a little, and it require some time. Also, would be good to test it on most pc I can before release it.

Tons of work are waiting...
