### ISSUE TITLE
Metal gear solid 1 mods new camera thrid person

### ISSUE THREAD

**Issue by forz0i** [VFansss/mgs2-v-s-fix#214]
Plase add mod thrid person view to MGS 1 PC moderne  mods caméra MGS1 and MGS 2
Thx

**Comment by VFansss** [comment]
I appreciate the advice, however it's out of scope to also fix MGS1 (especially because this fix can't work on the Master Collection Version)

**Comment by forz0i** [comment]
Plase add for Metal Gear Solid 1 version GOG port mods thrid person view

**Comment by forz0i** [comment]
Plase add mod thrid person view to MGS  1 gog version
