### ISSUE TITLE
I'm able to see trough the wall

### ISSUE THREAD

**Issue by MrMirvC** [VFansss/mgs2-v-s-fix#25]
Helllo, sorry for my bad english
What is happening is that sometimes I'm Able to see trough the walls, or, If I'm in a small room I can see the object outside the room but not the floor.

I'm playing on a laptop and Laptop mode is On,
Resolution is on 1280x720 (With this resolution I have still this bug)
Optimized 16:9 is on,
Fullscreen cutscenes is on
Maintain aspect ratio is On

Any advice? :\

**Comment by VFansss** [comment]
Can you provide me a screenshot, please?

**Comment by MrMirvC** [comment]
https://imgur.com/a/p7kGz

Here you go

**Comment by VFansss** [comment]
Quant'è bello capirsi!

Allora, e' un "bug" che in realtà...non lo è. Il gioco non è creato per il widescreen, e abilitando il fix per il widescreen (Maintain aspect ratio) è normale che si possa vedere "fuori" dallo schermo.

Nell'ultimo aggiornamento ho mitigato questa cosa aggiungendo il "FOV ottimizzato", che infatti è abilitato. Purtroppo c'è bisogno di annotare 'tutti' questi casi dove è possibile guardare fuori dallo schermo e aggiustare a mano la visuale, [altrimenti succedono casi tipo questo](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#common-problems--common-solutions) o come quello che mi hai mandato tu.

Purtroppo, nel primo caso me ne sono accorto e infatti non succede piu. Quello che mi hai mandato tu invece...mi è sfuggito.

Nella prossima release lo aggiusto, sperando non ce ne siano altri! 😃

**Comment by MrMirvC** [comment]
Va bene, grazie! :DD
Volevo segnalarti anche un altro bug che però non posso mostrarti lo screen perchè ci vuole un po' di tempo per arrivarci :o 
Io a MGS mi sto avvicinando da poco quindi non ricordo i nomi dei personaggi, quando impersoni Snake, nella parte dopo aver affrontato i soldati che ti sparano, Shalahaska (O qualcosa del genere...), per una piccola parte della cutscenes non si vede nulla!
Si intravedono alcuni modelli con textures mentre il resto è in un blu scuro

**Comment by VFansss** [comment]
Mi fido, anche perchè...lo conosco.

[Purtroppo è uno di quei bug che ritengo unfixabili, e ne parlo anche nel manuale](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode).

Non è detto che lo rimanga in eterno, ma come risolverli va decisamente fuori dalla mia portata 😞

**Comment by MrMirvC** [comment]
Capito.. Grazie dell'aiuto :D

**Comment by VFansss** [comment]
Dopo un po di smanettamento ho risolto il problema. Nella nuova build del fix dovrebbe essere tutto risolto. Se trovo altre location con lo stesso problema vedrò di risolvere!
