### ISSUE TITLE
R3 (sticks) not working

### ISSUE THREAD

**Issue by assassinboss** [VFansss/mgs2-v-s-fix#27]
So yeah, basically I can't aim. When I use ps2 or V scheme. In V scheme game recognizes the stick for first  person but not for aiming. No idea why. Any way to fix this?

**Comment by VFansss** [comment]
> V scheme game recognizes the stick for first person but not for aiming.

So if you press the stick (R3 button) it switch to first person, but then you can't aim (nothings move). Did I understand well?

Can you tell me what gamepad you have? Is an original xbox 360 gamepad?

**Comment by assassinboss** [comment]
I'm using original xbox 360 gamepad yes. 

So in V scheme when I press right stick, I enter first person mode and then I can move the view with left stick. But pressing left stick does nothing and same with ps2 scheme. So basically I can't aim or cancel the shoot. I can still shoot with x, but not being able to aim and move is a real deal breaker. Hope you can help me and thanks for such a quick answer.

**Comment by VFansss** [comment]
Let's go in order...

> when I press right stick I enter first person mode and then I can move the view with left stick

And this is normal.

> but pressing the left stick does nothing

And, in fact, it does have to do nothing.

> So basically I can't aim or cancel the shoot

In first person, to aim (pull out the gun) and point the pistol to something (move the visual) you must KEEP PRESSING the X button.

Then you can move the visual with the left stick and shoot releasing X.

This is 100% equal to the ps2 release! You can't move snake while doing it, and this is a game design choose), so after you done shooting you must press R3 again and move on!

If you want to cancel the shoot you have to KEEP PRESSED L3 (the left stick) and then release X.

Is anything out of ordinary in your mgs2? :grinning:

**Comment by assassinboss** [comment]
Oh now I get it. Jesus christ. sorry to waste your time. I guess I was remembering mgs 3, where you could hold people up and then aim at them and move at the same time. Again, sorry for wasting your time.

**Comment by VFansss** [comment]
In mgs2 you can actually aim AND move, but not in first person (again: is a game design choose).

You can do it in both layout if you keep pressed X and LB (on a xbox gamepad. Is L1 on a playstation gamepad).

Then you can keep the aim and move with left stick. Is just good to know.

I've written a chapter in the Wiki explaining these special actions, so is worthing a read if you want.

Don't worry, ask everything you want.

Have fun :)

**Comment by assassinboss** [comment]
And I just saw that you can also do that in your movement guide. Ok, i'm officially a retard haha. Thank you again so much for this fix, game works perfectly now
