### ISSUE TITLE
Freezes on intro screen

### ISSUE THREAD

**Issue by Keith94** [VFansss/mgs2-v-s-fix#3]
I just installed this game and the fix, when the game reaches "Konami presents" screen, video freezes but I can still hear audio. Is there a specific EXE I should be using or something else?

![mgs2_sse_2016-11-27_21-58-34](https://cloud.githubusercontent.com/assets/5490615/20657714/e26369d0-b4ec-11e6-9d3a-699d8cc4856a.png)

**Comment by VFansss** [comment]
In 400 unique downloads you are the first that has reported this problem °_°

There's no need for special .exe or something like that. Only a fresh install and the fix applied.
I've once encountered the same bug myself, but than it's never reappeared in almost 2 months of test.

Try to disable Widescreen Fix and/or 360 gamepad.

What cpu do you have?
More than one GPU? (Integrated counts, and are very important).

Applied it onto a fresh install?

**Comment by Keith94** [comment]
>Try to disable Widescreen Fix and/or 360 gamepad.

I get the same result with freezes.

>What cpu do you have?

I have Intel Core i5 3570k.

>More than one GPU?

Just one Nvidia GTX 680.

>Applied it onto a fresh install?

Yes. I also tested the game separately with only patch 2.0 + "PCGamingWiki patch" applied, but I still encounter the same bug... so not necessarily caused by "V's fix", but a general issue. I will try restarting my computer in a bit.

**Comment by VFansss** [comment]
The only way to understand what cause it is to look if it's still hung up after every one of each passage (after a fresh install):

1) Apply the creative alchemy patch. Find it here:
https://github.com/VFansss/mgs2-v-s-fix/raw/master/mgs2%20v's%20fix/Resources/2_audio_fix.zip

2) Install the official 2.0 patch. You can find in into pcgamingwiki patch archive.

Try this. If you need a no-cd exe use the Geforce fix. ALSO try to disable the integrated gpu from the bios.

**Comment by Keith94** [comment]
Okay, I installed Creative Alchemy patch, ran the game, game freezes. Then I installed official patch, ran the game, still freezes. I did not do anything in bios however.

I assume it's just a problem with my system if nobody else has this problem..

**Comment by VFansss** [comment]
Try to disable integrated GPU from the bios. It's a very strange problem, honestly. Is unrelated to the fix I think (and this is good :p) but it's very irritating.

Use the original config tool and disable everything you see. Don't use windowed mode,also. There must be a way to get the game started on your system...

**Comment by Keith94** [comment]
Well, I figured out that pressing Enter once after the game starts will skip all the opening movies, so it bypasses the hang issue and brings me to the title screen. :)

So now I wonder, is there a permanent way to skip all intro videos? Probably a slim chance but worth a shot.

**Comment by VFansss** [comment]
°_°

Video are packed inside a .dat files. I don't know how to decrypt it, probably there's some modder tool online. Then maybe someone can substitute it with an empty one or something like that...

Again: °_°

**Comment by Keith94** [comment]
Aha well no worries then. Thank you for the support btw.

I will try out the rest of the game at some point later.

**Comment by VFansss** [comment]
I solved this problem: it's a codec issues.

Fast solution? [K-lite codec pack](https://www.codecguide.com/download_kl.htm). Try the "Full" installation. Watch out if it install some unwanted things during installation phase (= like chrome or yahoo searchbar) and follow all the screen instruction. It automatically fix any missing/broken codec problem, also.

It's a very good codec pack. I never encountered that problem cause...I always install it on any PC I have.

This should solve any issues with freezing FMV, broken/missing video on codec or things like that...
