### ISSUE TITLE
Right analog stick not working

### ISSUE THREAD

**Issue by oj10sam** [VFansss/mgs2-v-s-fix#32]
Hello, I cannot seem to get my right stick working and its preventing me from advancing

**Comment by VFansss** [comment]
Hi!

What layout have you choosed? (V's or PS2)

You have an original xbox 360 gamepad or an xbox1 gamepad?

Have you tried to start the fix with admin rights?

**Comment by oj10sam** [comment]
I am using a PS2 controller thru a usb adapter. Ive tried both layouts and I tried admin rights. I am now wondering if there is a way to bypass the controller input so i can just use a game profiler and map the keys to my controller. I mapped them but the fix seems to be overriding my app and messing up my controls still.

**Comment by Lion4K** [comment]
If you use some  dinput to xinput translator you can get the game to use the controller as if it were a xbox controller.
If you have the drivers to your adapter you can even make it vibrate using the translator.

**Comment by Lion4K** [comment]
I've used this pack with my old PS1 controller, at that time I had the driver.

I was able to play any game that used xInput and with vibration.

I still have it in my skydrive, if you want it.
https://1drv.ms/u/s!AnboK7YPAUuag6YoHSgVXvZt0Ovz0w

**Comment by Lion4K** [comment]
just drag and drop everything next to the exe of the game.

**Comment by oj10sam** [comment]
do i have to pull the files out of the src folder as well or just drop that folder in as is?

**Comment by Lion4K** [comment]
hm yeah it was supposed to say that controller was connected.

**Comment by oj10sam** [comment]
which ini file?

**Comment by Lion4K** [comment]
the only ini file included in my pack.

**Comment by oj10sam** [comment]
im sorry but whats the name of the file, all i have are DLL's?

**Comment by Lion4K** [comment]
xbox360cemu.ini

**Comment by VFansss** [comment]
The last build of the fix will deploy the default input configuration, if gamepad support is disabled.

This would have avoided the problem mentioned above.
