### ISSUE TITLE
Savedata vanishing/corrupted

### ISSUE THREAD

**Issue by Junkboy626** [VFansss/mgs2-v-s-fix#33]
I'm an italian player so please forgive my grammar mistakes.
My issue is about the saves, which are starting to disappear or being corrupted. What happens is simple: I start a new game and create a new save slot. Then i continue into the game and obviously i have to overwrite the first save. But, when i close the game and I restart it, in the load game menu i can only see the first save. The strange thing is that, while I play, the subsequent saves works just fine. I tried to take a look at the /savedata folder of the game and it shows only /GameData00 even if I can see the 01 slot into the game. Can't find anything similar around, so i thought that this could be helpful for you and for other players who may encounter such a frustrating issue.
I'll continue updating this thread in case I'll found something new about this issue.
However, thanks for your attention and patience and for the great work. Your fix made my dream come true. Have a nice day!

**Comment by VFansss** [comment]
I'm an italian programmer, perciò occasionalmente possiamo parlare in italiano!

Hai avviato il fix con i privilegi d'amministratore? (Tasto destro -> Avvia con privilegi amministratore).

Oltretutto puoi per cortesia provare disattivando sia il gamepad, sia "l'aspect ratio fix" e sia l'anti aliasing? (Dubito fortemente che il problema sia dovuto a quello, ma...)

**Comment by Junkboy626** [comment]
Salve VFan!
Grazie per la velocissima risposta.
Ebbene il problema sembra risolto. Considerando che eseguivo già MGSSetup da amministratore e avevo l'antialiasing disattivato, per esclusione spero sia l'aspect ratio fix, perché se il problema è la configurazione del gamepad non posso usare i grilletti e la cosa mi ucciderebbe.
Adesso i salvataggi rimangono, e riesco a vedere anche lo slot Game Data 01 nella cartella /bin.

**Comment by VFansss** [comment]
Bhe, se adesso che il widescreen fix è disattivato funziona tutto  correttamente non ti resta che provare a riattivarlo.

Se quando è attivo il problema si ripresenta so per certo su cosa lavorare, e dovrebbe essere molto piu semplice da risolvere!

**Comment by Junkboy626** [comment]
Proverò domattina e ti aggiornerò allora!

**Comment by Junkboy626** [comment]
Ho provato in due modalità, per escludere coincidenze di ogni tipo.
- Aspect Fix Ratio: OFF; Controller: ON;
- Aspect Fix Ratio: ON; Controller: OFF;
In entrambi i casi sembra funzionare correttamente. Ma non è un problema facile da riprodurre, potrebbe succedere nuovamente in futuro.
Ulteriori dettagli potenzialmente utili:
- Uso i comandi PS2
- Nell'aspect ratio, se attivo, solo l'opzione 'optimized 16:9 FOV' è ON, come di default
- Il mio computer è un laptop, con scheda grafica dedicata e, come consigliato sulla wiki, la modalità laptop è attiva

**Comment by VFansss** [comment]
Il punto è che finchè non sono sicuro di cosa causi il problema...non posso aggiustare nulla!

Non ho riscontrato il bug, quindi se hai pazienza sei l'unico che potrebbe aiutarmi.

> In entrambi i casi sembra funzionare correttamente. Ma non è un problema facile da riprodurre, potrebbe succedere nuovamente in futuro

Pensavo che prima succedesse SEMPRE.

Tirando ad indovinare: non mi pare un bug che si verifica a volte si e a volte no.

Prova a ri-abilitare sia Aspect Ratio Fix e sia il Controller e riprovare.

Visto che, se abilitati assieme, le due librerie coesistono senza saperlo potrebbe essere quella la causa.

Però purtroppo non riesco a replicare la cosa sul mio pc, e quindi non saprei come fare.

**Comment by Junkboy626** [comment]
È un problema un po'strano

**Comment by Junkboy626** [comment]
Il problema è un po' strano. In pratica in una stessa partita, se sovrascrivo più volte uno stesso salvataggio, capita, ma non proprio sempre, che i successivi salvataggi non vengano considerati. Inoltre il salvataggio 01 non appariva nella cartella /savedata nonostante fosse visibile e utilizzabile in-game.
Ti dico che non capita sempre, o comunque non ne sono sicuro al 100%, perché ho fatto tutto l'episodio tanker in un'unica partita, salvando più volte sullo stesso slot ma senza mai chiudere il gioco è non ho avuto problemi. Arrivato al plant invece ho fatto un salvataggio dopo poche aree e poi ho chiuso il gioco. Una volta rientrato solo l'ultimo salvataggio, quello sul plant, risultatava inesistente. Si era fermato al tanker.
Scusa la lunghezza, ma volevo essere il più chiaro possibile.
In ogni caso più tardi riproverò con entrambe le impostazioni attivate e ti farò sapere.

**Comment by VFansss** [comment]
Può persino essere che si tratti di un bug del gioco originale e che non sia dovuto dal fix. Considerando quanto fa schifo il port...potrebbe anche essere. Strano che non me ne sia accorto, ma...

Sti 2/3 giorni sono super-impegnato quindi non posso fare i test di persona ma la prossima settimana pazientemente cercherò di venirne a capo.

Se proprio hai voglia puoi provare a [scaricare qualche versione vecchia](https://github.com/VFansss/mgs2-v-s-fix/releases) come la 1.03.2 o addirittura la 1.02 e vedere se il problema si presenta anche con quelle.

Se lo fai, PRIMA di installare un V's Fix 'vecchio' ricordati di disattivare (Dal fix 'corrente') sia 'Aspect ratio fix', sia il gamepad e sia l'anti-aliasing e premere SAVE. E' importante.

**Comment by Junkboy626** [comment]
Guarda, hai già fatto tanto, per me non c'è problema.
Anche perché, almeno per adesso, i salvataggi funzionano correttamente. Magari è un problema del porting in sé che si attiva a causa di chissà quale particolarità del mio computer.
Se ad un prossimo playthrought dovesse ripresentarsi nello stesso punto della storia, o successivamente in questa stessa partita, aggiorno questo thread.

Grazie ancora per l'interesse.

**Comment by Junkboy626** [comment]
Finalmente ho scoperto l'origine del problema, almeno sul mio pc.
In pratica avviando il gioco dalla shortcut sul desktop, mi viene chiesta l'autorizzazione del Controllo dell'account utente e non ho alcun problema. Ma se lo avvio dalla ricerca della Barra delle Applicazioni, come spesso faccio con molti altri programmi, non mi viene richiesto di autorizzare il programma e i salvataggi 00 e 01 tornano a quel salvataggio Normale che feci diverse settimane fa. Come se richiamasse una versione precedente dello stesso file (che si chiama allo stesso modo infatti).

Spero possa esserti utile quest'informazione.

**Comment by VFansss** [comment]
In realtà immaginavo fosse un problema di UAC e di permessi.

Fai un esperiemento:

* Abilita i file nascosti
* Vai in C:\Users\[TUONOMEUTENTE]\AppData\Local\VirtualStore

C'è mica qualcosa di familiare dentro?

**Comment by Junkboy626** [comment]
Eh sì! Hai trovato i salvataggi perduti!

**Comment by VFansss** [comment]
In effetti avrei dovuto pensarci prima, ad un'eventualità del genere.

Il problema è il cosiddetto "VirtualStore", ovvero una diavoleria Microsoft che permette ai programmi che non hanno privilegi d'amministratore (cioè mgs2.exe) di scrivere i propri files dentro una directory (C:\Program Files\KONAMI\) che RICHIEDE privilegi d'amministratore.

Se avvii il gioco dalla Barra delle Applicazioni (che presumo sia il menu Start) questo VirtualStore si 'attiva', non ti vengono chiesti privilegi particolari e il gioco (che vuole leggere i files dalla sua cartella in Program Files) verrà reindirizzato in maniera transparente su quella cartella particolare.

Se invece lo avvii dal Desktop, avvii mgs2_sse.exe oppure dal Fix ti appare l'UAC, tu rispondi di si, ti vengono dati i privilegi d'amministatore e quindi il gioco ha l'autorizzazione per leggere/scrivere i savegames dentro la sua cartella.

Ovviamente le due cartelle "fisiche" non hanno gli stessi files, e quindi in pratica si crea questo problema.

Non mi hai specificato che sistema operativo hai, ma presumo a questo punto che sia Windows10.

Non ho mai riscontrato lo stesso problema perchè avvio il gioco o dal fix o direttamente, e quindi ho sempre i privilegi piu alti per avviarlo. Come risolvere? Eh, bel casino.

Adesso che mi hai chiarito la situazione so cosa dovrei correggere, ma non so precisamente come. Mi dovrò inventare qualcosa.

Sei stato preziosissimo :)

**Comment by VFansss** [comment]
Dovrebbe, e dico dovrebbe, essere risolto nell'ultima release
