### ISSUE TITLE
kb.ini is missing

### ISSUE THREAD

**Issue by VenomMeme** [VFansss/mgs2-v-s-fix#35]
I just got this and when I tried to load it up, I got an error that said "Failed access to file GAME DIRECTORY/./kb.ini" I've looked for the file and nothing showed up. Any help?

**Comment by Lion4K** [comment]
[kb.ini.zip](https://github.com/VFansss/mgs2-v-s-fix/files/1874358/kb.ini.zip)

You can have a copy of mine, hope it helps.

**Comment by VFansss** [comment]
Hi!

Can you please activate the [debug mode](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) and send me the file you get on your desktop?

Also, if you want to provide me a screenshot I would be very pleased :D

**Comment by VenomMeme** [comment]
Thanks Lion. It worked, but now it says that kbs.ini is missing.

**Comment by VenomMeme** [comment]
VFanasss, how exactly do I access debug mode? I've checked the instructions on this page and nothing worked.

**Comment by VenomMeme** [comment]
Thank Lion for helping me but I just got a new error. Here I'll type it for you: "Failed access to file {GAME DIRECTORY}/../cdrom.img/stage/init/data.cnf" I'm sorry if I'm annoying you.

**Comment by Lion4K** [comment]
At this point I would reccomend you reinstalling the game.

**Comment by Lion4K** [comment]
Idk where you acquired your copy but I got mine from a famous website that worked wonderfully.

**Comment by Lion4K** [comment]
name of the copy is

Metal.Gear.Solid.2.Substance.v2.0-SiMON

**Comment by Lion4K** [comment]
Sent 07-24 2012, Size 3.77 GiB, UP by .BONE.

**Comment by VenomMeme** [comment]
I've decided to give up on this. Thank you so much for the help. I really appreciate it.

**Comment by Lion4K** [comment]
if you decide to use the copy i recommended, you simply need to download, mount the iso, install it, and apply VFansss patch.

Do not follow any procedure included with the downloaded as it is highly outdated.

**Comment by VenomMeme** [comment]
Okay, Thank you. I'll take note of that.
