### ISSUE TITLE
There is a problem with the hardware structure

### ISSUE THREAD

**Issue by Neo941** [VFansss/mgs2-v-s-fix#36]
There is a problem with the hardware structure.

----------------------------------------------------------------------------------

MGS2_VFix_debug.txt message:

12.48.34.901 -> [!][!][!][!][!][!][!][!][!][!][!][!]
12.48.34.901 -> [!]
12.48.34.901 -> [!] Fix started at 09/04/2018 22:48:34 (UCT)
12.48.34.901 -> [!] forbidStart is false. Starting winform
12.48.35.073 -> [+] Form1 constructor has done. Waiting user input.

----------------------------------------------------------------------------------

I've obtained this error after running MGS2 for the twice.

**Comment by VFansss** [comment]
Hi!

Have you tried to configure the game before pushing 'PLAY'?

**Comment by Neo941** [comment]
Hi!

Yes, I did it. Unfortunately, this error shows it every time after the
execution of MGS2.



2018-04-10 8:34 GMT+02:00 Alessio Di Giacomo <notifications@github.com>:

**Comment by VFansss** [comment]
Ok. Can you please post here the content of the file 'Configuration_file.ini'?

You can find it inside the 'bin' folder, where you copied the fix. You can open it using a simply text editor. Thanks.

**Comment by Neo941** [comment]
Hi!

Sorry, but I had not seen your answer.
Anyway, this is the file "Configuration_file.ini".



2018-04-10 10:09 GMT+02:00 Alessio Di Giacomo <notifications@github.com>:

**Comment by Neo941** [comment]
About the controls in MGS2.
I suggest to use these controls:



2018-04-14 1:06 GMT+02:00 Andrea Di Peco <dipecoandrea@gmail.com>:

**Comment by Neo941** [comment]
I have a question.
Are you italian?

2018-04-14 1:25 GMT+02:00 Andrea Di Peco <dipecoandrea@gmail.com>:

**Comment by VFansss** [comment]
Eh si!

Comunque sarò scemo io ma non vedo il contenuto dei due file che ti avevo chiesto!

**Comment by Neo941** [comment]
Ho capito. Domanda scema che sto per farti.
Hai usato il blocco note per aprirli?

2018-04-14 15:39 GMT+02:00 Alessio Di Giacomo <notifications@github.com>:

**Comment by Neo941** [comment]
Te lo chiedo perché ho usato quello per aprire i 2 files.

Il giorno 14 aprile 2018 15:41, Andrea Di Peco <dipecoandrea@gmail.com> ha
scritto:

**Comment by Neo941** [comment]
Riuscito a visualizzarli?

Il giorno 14 aprile 2018 15:54, Andrea Di Peco <dipecoandrea@gmail.com> ha
scritto:

**Comment by VFansss** [comment]
Guarda, sono sicurissimo che non mi hai mandato nulla. Sopra vedo solamente il tuo post:

Sorry, but I had not seen your answer. Anyway, this is the file "Configuration_file.ini".

Ma sotto non c'è nulla. Anzi, vedo addirittura che hai postato un pezzo della mail di alert di GitHub.

Stai facendo un po di confusione. Apri i file che ti ho indicato su, copia tutto il contenuto nella risposta qui su GitHub e vediamo come posso aiutarti.

**Comment by Neo941** [comment]
Non 3 possibile, mi ricordo benissimo di avere allegato il file. Ma se vuoi
adesso ci riprovo.
Aspetta.

Il sabato 14 aprile 2018, Alessio Di Giacomo <notifications@github.com> ha
scritto:

**Comment by Neo941** [comment]
Ok. Eccolo.

Il giorno 14 aprile 2018 18:25, Andrea Di Peco <dipecoandrea@gmail.com> ha
scritto:

**Comment by Neo941** [comment]
Dimmi se l'hai ricevuto?

Il giorno 14 aprile 2018 19:35, Andrea Di Peco <dipecoandrea@gmail.com> ha
scritto:

**Comment by Neo941** [comment]
Poi scusa... io non ho postato nessun pezzo della mail di alert di GitHhub.

Il giorno 14 aprile 2018 19:35, Andrea Di Peco <dipecoandrea@gmail.com> ha
scritto:

**Comment by Neo941** [comment]
forse ho capito il perché non ricevi nessun file.
Il fatto è che io ti sto scrivendo per via email (ossia gmail).

Il giorno 14 aprile 2018 20:07, Andrea Di Peco <dipecoandrea@gmail.com> ha
scritto:

**Comment by Neo941** [comment]
Ecco i files (sia quello di configurazione che dei controlli):

[MGS2.zip](https://github.com/VFansss/mgs2-v-s-fix/files/1911289/MGS2.zip)

**Comment by Neo941** [comment]
ti chiedo scusa, ma cerca di capire ma sono su github.
Di conseguenza devo ancora imparare a interagire con la piattaforma.

**Comment by VFansss** [comment]
Perfetto, non fa nulla, impariamo tutti.

Però non mi hai mandato il file **mgs2.ini**, che è molto importante. Per favore allegamelo.

**Comment by Neo941** [comment]
[mgs2.ini .zip](https://github.com/VFansss/mgs2-v-s-fix/files/1912366/mgs2.ini.zip)

**Comment by Neo941** [comment]
Ciao,

Ho provato a disabilitare l'anti-aliasing, ma non mi viene data la
possibilitá di farlo (siccome quando cerco di salvare le impostazioni,
ottengo solo una schermata di errore) o in ogni caso se ci riesco non
cambia nulla.

Il domenica 15 aprile 2018, Alessio Di Giacomo <notifications@github.com>
ha scritto:

**Comment by VFansss** [comment]
Scusa, che significa "una schermata di errore"?

Quale errore? Cosa c'è scritto?

Hai provato ad avviare il fix avendo i privilegi d'amministratore? (clicca con il tasto destro sul file e scegli " Avvia come amministratore").

**Comment by Neo941** [comment]
La schermata di errore in questione diceva che per salvare le impostazioni,
dovevo avere i privilegi d'amministratore.
Il bello è che quando avviavo il tool con "Avvia come amministratore" e poi
cliccavo su "SAVE" dopo aver configurato i vari parametri, mi dava
ugualmente quel tipo di errore.

2018-04-15 22:50 GMT+02:00 Alessio Di Giacomo <notifications@github.com>:

**Comment by VFansss** [comment]
> mi dava ugualmente quel tipo di errore

Intendi un errore riguardante i privilegi d'amministratore, o il fatto che il gioco da "problem with hardware structure" blabla?

Se quando premi save ottieni un errore c'è un problema di diritti sul computer.

Avvia il fix in modalitá debug E con i diritti di amministratore, poi premi SAVE.

Dopodichè allegami il file di debug che trovi sul desktop.

Sono sicuro che il tuo pc sta vietando l'applicazione di qualche impostazione e da una serie di problemi.

**Comment by Neo941** [comment]
Mi riferisco a quello dei privilegi di amministratore.
Poi sì, ho provato anche ad avviare il tutto con la modalità debug, ma in
quelo caso mi appare il famoso errore "there is a problem with the hardware
structure".
Tra l'altro, il file di debug te l'ho già inviato sotto forma di messaggio
(sarebbe il primissimo messaggio in lingua inglese che ti avevo scritto).


Il giorno 15 aprile 2018 23:15, Alessio Di Giacomo <notifications@github.com

**Comment by Neo941** [comment]
il contenuto del file debug è questo:


MGS2_VFix_debug.txt message:

12.48.34.901 -> [!][!][!][!][!][!][!][!][!][!][!][!]
12.48.34.901 -> [!]
12.48.34.901 -> [!] Fix started at 09/04/2018 22:48:34 (UCT)
12.48.34.901 -> [!] forbidStart is false. Starting winform
12.48.35.073 -> [+] Form1 constructor has done. Waiting user input.

Il giorno 15 aprile 2018 23:41, Andrea Di Peco <dipecoandrea@gmail.com> ha
scritto:

**Comment by VFansss** [comment]
Ascolta: sono sicuro che non hai fatto quello che ti ho suggerito.

Mi hai ripostato di nuovo il log che mi hai scritto sopra, paro paro con tanto di data uguale.

Cancella il file sul desktop, poi fai quello che ti ho suggerito, cioè **avvia il fix in modalitá debug CON i diritti di amministratore e POI premi save**

Se lo fai è impossibile che ti rispunti lo stesso messaggio che mi hai postato gia.

**Comment by VFansss** [comment]
Il fix adesso richiede i privilegi di amministratore anche solo per essere avviato.

Dovrebbe risolvere parecchi casini a livello di diritti, tra cui probabilmente questo issue.

**Comment by Neo941** [comment]
Ciao,

Scusa se non mi sono fatto sentire per un bel po'.
In ogni caso in questi giorni, se mi sarà possibile, riproverò il fix.


2018-05-01 13:05 GMT+02:00 Alessio Di Giacomo <notifications@github.com>:

**Comment by Neo941** [comment]
Ciao,

Scusa se non mi sono fatto sentire per un bel po'.
In ogni caso, se mi sarà possibile, in questi giorni riproverò il fix.

Il giorno 2 maggio 2018 12:32, Andrea Di Peco <dipecoandrea@gmail.com> ha
scritto:

**Comment by VFansss** [comment]
Ho fatto delle modifiche al codice ma non ho ancora rilasciato la nuova versione.

Quindi se lo riprovi ora al massimo otterrai lo stesso risultato.

Vedremo in futuro con la versione nuova...
