### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by DoctorDizzyspinner** [VFansss/mgs2-v-s-fix#39]
So I applied the fix, and went to start up the game. It worked well, but the patch didn't seem to have applied. I went to settings, and booted up the game again. Then it crashed. Whenever I start up the game, it crashes. How do I fix this?
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2065036/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
Please open the fix, set your game and press SAVE. Then send me the MGS2_VFix_debug,txt.

Also, inside the game folder you can find a file called last.log. Please send me that too!

**Comment by DoctorDizzyspinner** [comment]
[last.log](https://github.com/VFansss/mgs2-v-s-fix/files/2065042/last.log)
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2065043/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
Ok, I should had to specify better :D

Delete the MGS2_VFix_debug.txt file, open the Fix, open SETTINGS, press SAVE and THEN send me the debug file again.

Also, try you want try selecting another VGA from the list.

**Comment by VFansss** [comment]
Check [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Settings-Menu#resolution-tab) link from the guide.

You don't have more VGA on the list marked with '6'?
Are you playing from laptop?

And most important: are you installed the game from the original DVD or you run it from a portable installation?

**Comment by DoctorDizzyspinner** [comment]
I installed it from a portable installation, and even though I'm using a PC, there aren't any more VGA on the list.

**Comment by VFansss** [comment]
Do this test: Go to C:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance

This folder exist? If yes: there is something inside?

**Comment by DoctorDizzyspinner** [comment]
no, the file does not exist.

**Comment by VFansss** [comment]
Ok, here's the deal: probably something freaked out because someone run the game before you on another system, and you used its installation folder.

Try to delete these files:
- _audio_fix_applied.sss
- _fixed_exe_applied.sss
- _patch2.0_applied.sss
- Configuration_file.ini
- mgs2.ini

If you can please try to install the game from the original DVD, because trying to pinpoint issues for a portable installation is very time ineffective!

**Comment by DoctorDizzyspinner** [comment]
That worked! Thank you!

**Comment by VFansss** [comment]
Good 😄 

Have fun!
