### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by Unleashed2k** [VFansss/mgs2-v-s-fix#4]
I just wanted to comment and say this is an awesome project. I can't wait for you to add PC control support as it's the only missing feature at the moment :)

**Comment by Keith94** [comment]
@VFansss How about adding multiple controller configurations to the launcher, especially the ["modern" layout detailed here](http://pcgamingwiki.com/wiki/Metal_Gear_Solid_2:_Substance#Controller_support) (so we can replace that fix entirely if it's any good ;)). Or even full rebinding of buttons if possible.

**Comment by VFansss** [comment]
> I just wanted to comment and say this is an awesome project. I can't wait for you to add PC control support as it's the only missing feature at the moment :)

Thanks pawl! Every greetings is so much appreciated!

What do you mean with "PC control support"?
Keyboard? Or a "generic gamepad"?

Keyboard are very easy to implement. It's just VEEEERY time consuming. I don't think there are a lot of people playing mgs with keyboard, so I simply put it and the end of my "ToDo" list. Maybe in a future :)  For the second one...check below reply.

> @VFansss How about adding multiple controller configurations to the launcher, especially the "modern" layout detailed here (so we can replace that fix entirely if it's any good ;)). Or even full rebinding of buttons if possible.

That "modern layout" is simply the default one on PS2.
It was the first I thinked when I started with the project.

What's the problem?
It's hard to "wrap" gamepad input for the game. Game has problem with vibrations and triggers, and I found a perfect solution (XInput Plus project) that solve in a brilliant way the problem,expecially for 360/One controllers! But for others gamepad?

That 'modern layout' you say require....XPadder. It's a very good software; so good that:
1) Isn't freeware. It cost €€€ (or $$$,or £££ or whatever)
2) also thanks to above: isn't open source/licence free, and I can't implement inside my fix.

This basically make a conflict with mine, that:
1) Is free.
2) It's as easy as 3 (or 4) clicks.

There's some solution I thinked, but any of them perfectly satisfy my requirements:

1) Can I insert an XPadder pre-made layout -> but you have to use XPadder and load it yourself -> €€€
2) Can I made from scratch a software that bind gamepad-keyboard button -> Very time consuming, and require an additional software open when playing. Kinda weird.
3) Use an external driver. It work good but must be compatible with your OS, and require....installing a virtual gamepad. Kinda conflict with requirement number 2. Also licence problem?

As you see any solution is very good. Maybe in future I will found something that made it simply, free and relatively easy. 

Until than I can't afford anyone spend money (even for a good software. I love XPadder) or spend too much time configuring things...

**Comment by Keith94** [comment]
>That "modern layout" is simply the default one on PS2.

Ahh okay, I just assumed most players would be more "familiar" with this modern/PS2 layout, but I'm sure your custom layout does the job just as good.

FYI, [Antimicro](https://github.com/AntiMicro/antimicro) is an open source alternative to Xpadder; I may add it to the wiki page later if needed...

Thanks for the reply.
