### ISSUE TITLE
Downloaded new 1.05 update for MGS2S PC V's Fix and now it crashes every time I try to start

### ISSUE THREAD

**Issue by PleasuringYou** [VFansss/mgs2-v-s-fix#40]
Worked fine but wanted to get the new 1.05 update since it added the PS4 remote option and when I finished installation, the game no longer starts. The update looks as if it's been activated in the settings but the game does not launch anymore. It just opens a black screen for a couple of seconds and then it closes. Here are the debug details: 

08.16.22.379 -> [!][!][!][!][!][!][!][!][!][!][!][!]
08.16.22.381 -> [!]
08.16.22.381 -> [!] Fix started at 6/8/2018 2:16:22 AM (UCT)
08.16.22.385 -> [!] forbidStart is false. Starting winform
08.16.22.480 -> [+] Form1 constructor has done. Waiting user input.
08.16.59.934 -> [+] Start game button pressed
 Please help me with this issue, I love this game and your fix and i'm pretty bummed out that idk how to resolve this.

**Comment by VFansss** [comment]
Hi!

Try to delete these files:
- _audio_fix_applied.sss
- _fixed_exe_applied.sss
- _patch2.0_applied.sss
- Configuration_file.ini
- mgs2.ini

And see if its working 😄

**Comment by PleasuringYou** [comment]
Tried it and same thing happens unfortunately.

**Comment by VFansss** [comment]
Ok, let's do this:

- Leave enabled the debug mode
- Delete the debug file on desktop
- Open the Fix
- Press 'SETUP' and then 'SAVE'
- Open the game

Then send me the debug detail AND the last.log file you find inside the game directory.

Please do all in this order!

**Comment by PleasuringYou** [comment]
Debug detail:
02.51.47.367 -> [!][!][!][!][!][!][!][!][!][!][!][!]
02.51.47.367 -> [!]
02.51.47.367 -> [!] Fix started at 6/15/2018 8:51:47 AM (UCT)
02.51.47.367 -> [!] forbidStart is false. Starting winform
02.51.47.468 -> [+] Form1 constructor has done. Waiting user input.
02.52.08.826 -> [ ] Settings button pressed
02.52.08.826 -> [ ] .ini contain a valid configuration. Loading from it...
02.52.08.826 -> [ ] Information from .ini succesfully loaded into setupper!
02.52.08.863 -> [ ] Settings - settings from internal config correctly attached to setupper
02.52.08.879 -> [+] Settings has been displayed.
02.52.12.911 -> [ ] Save button pressed
02.52.12.995 -> [ ] InternalConfig succesfully exported into Configuration_file.ini
02.52.17.515 -> [ ] grantAccess has returned True
02.52.17.516 -> [ ] InternalConfig succesfully exported into mgs2.ini
02.52.17.516 -> [D] ----------
02.52.17.516 -> [D] Printing InternalConfig:
02.52.17.516 -> [D] - VGA List:
02.52.17.516 -> [D] NVIDIA GeForce GTX 780 Ti
02.52.17.516 -> [D] Key: Height -> Value: 900
02.52.17.516 -> [D] Key: Width -> Value: 1600
02.52.17.516 -> [D] Key: WideScreenFIX -> Value: true
02.52.17.516 -> [D] Key: GraphicAdapterName -> Value: NVIDIA GeForce GTX 780 Ti
02.52.17.516 -> [D] Key: WindowMode -> Value: false
02.52.17.516 -> [D] Key: LaptopMode -> Value: false
02.52.17.516 -> [D] Key: FullscreenCutscene -> Value: true
02.52.17.516 -> [D] Key: OptimizedFOV -> Value: 16:9
02.52.17.516 -> [D] Key: EnableController -> Value: DS4
02.52.17.516 -> [D] Key: PreferredLayout -> Value: V
02.52.17.516 -> [D] Key: RenderingSize -> Value: high
02.52.17.516 -> [D] Key: ShadowDetail -> Value: high
02.52.17.516 -> [D] Key: ModelQuality -> Value: high
02.52.17.516 -> [D] Key: RenderingClearness -> Value: high
02.52.17.516 -> [D] Key: EffectQuantity -> Value: high
02.52.17.516 -> [D] Key: BunchOfCoolEffect -> Value: true
02.52.17.516 -> [D] Key: MotionBlur -> Value: true
02.52.17.516 -> [D] Key: AA -> Value: false
02.52.17.516 -> [D] Key: SoundAdapterName -> Value: Primary Sound Driver
02.52.17.516 -> [D] Key: Quality -> Value: high
02.52.17.516 -> [D] Key: SE -> Value: high
02.52.17.516 -> [D] Key: SoundQuality -> Value: high
02.52.17.516 -> [D] Key: FixAfterPlaying -> Value: true
02.52.17.516 -> [D] END
02.52.17.567 -> [+] Save has been saved (!)
02.52.26.327 -> [+] Start game button pressed

last.log:
Log Name:C:\Users\Tevita\AppData\Local\Temp\logA832.tmp
[ FS_PATH_CTGR_INI ]: C:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance\bin/.
[ FS_PATH_CTGR_STAGE ]: C:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance\bin/../cdrom.img
[ FS_PATH_CTGR_STREAM ]: C:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance\bin/../cdrom.img
/*-- Graphics System Daemon Start --*/
Selected Device:NVIDIA GeForce GTX 780 Ti
Device[0]:NVIDIA GeForce GTX 780 Ti
Device[1]:NVIDIA GeForce GTX 780 Ti
Video Device:
	Driver         :nvldumd.dll
	Description    :NVIDIA GeForce GTX 780 Ti
	Driver Version :00170015000D2375
	VendorId       :000010DE
	DeviceId       :0000100A
	SubSysId       :131419DA
	Revision       :000000A1
Create Device:
	DeviceType     :1
	BehaviorFlags  :00000054
	Windowed       :0
	FullScreen_RefreshRateInHz :0
	FullScreen_PresentationInterval :1
	BackBuffer     :(1600, 900)
	MultiSampleType:0
	SwapEffect     :1
	BackBufferFormat:22
	BackBufferCount:2
	EnableAutoDepthStencil:1
	Flags          :00000001
DG_Adju

**Comment by VFansss** [comment]
Hi!

Another user has a similar issues and I'm pinpointing the cause out of it.

Can you please re-download the latest version of the fix (the 1.05.2) and see if the situation is solved?

I'm sorry for these issues 😬

**Comment by VFansss** [comment]
EDIT: Can you also try to delete the d3d8.dll file you can find inside the game directory, and then try to start the game using the mgs2_sse.exe executable?
