### ISSUE TITLE
R3/L3 not working on Dualshock 4

### ISSUE THREAD

**Issue by vrubayka** [VFansss/mgs2-v-s-fix#42]
Hello,
I have a DS4 and I use a program called DS4Windows to make the Windows think it's an XBOX controller, therefore support it. I tried running the game with - Xbox - PS2 Type - and every button works correctly except for R3 and L3 - game doesn't react to them at all. Is there a way to fix this issue? Maybe somebody got it running with a DS4 using other software.

**Comment by VFansss** [comment]
Hi!

If you have the latest version (the 1.05.3) you can directly select the ds4 from the "controller tab".

It shouldn't even need any external software

**Comment by vrubayka** [comment]
Just tried turning off all controller-related software and launched the game with the ps4 preset - now the controller doesn't work at all. Xbox preset as well. The issue is that Windows doesn't recognize DS4 on it's own without other software, at least that's what I read. I've been using DS4Windows in pair with XInput for a long time now and every old game worked. Did anybody actually got it working on its own without third party software?

**Comment by VFansss** [comment]
The truly issue is that I don't own a DS4, neither I never have touched one. So it was quite hard to figure how is working, without actually possessing it.

Please do this test: please apply your favourite DS4 layout, press SAVE and then manually delete the Dinput.dll and Dinput8.dll files from the game main directory!

**Comment by vrubayka** [comment]
Good idea, but didn't work. I think the reason is the way the game itself detects the sticks being pressed, or rather it not detecting them and the fix has nothing to do with the problem. But is there a way I can remap the actions that are mapped to R3/L3 to Left Dpad and Right d-pad(After all you don't need them when there are sticks) and from there on i'll try doing something with xinput to make pressing L3 and R3 actually prss the 'remapped' actions of dpads?

**Comment by VFansss** [comment]
Sorry If I don't straight answer your questions, but please do this last test: use ds4windows this time, apply one ds4 layout, press save and then delete dinput.dll and dinput8.dll.

If even this doesn't work...I'm in trouble!

**Comment by vrubayka** [comment]
![default](https://user-images.githubusercontent.com/35918204/41676419-b2e550d4-74c5-11e8-9ae2-b20a11f00ea9.png)
That's what I mean

**Comment by vrubayka** [comment]
No-no I did it exactly as you said, the fix overrides the xinput dlls so i deleted them and made new ones fitted for my controller with the xinput program and ran the game afterwards - the r3 and l3 still don't work.

**Comment by vrubayka** [comment]
So I checked the Xinput and I mapped the L3 and R3 to DPad Left and right and it worked, L3 and R3 made Snake move left and right so the question is, can I remap the L3 and R3 actions to dpads and then I'll be able to remap the Xinput to make pressing R3 and L3 actually do actions of dpads.

**Comment by vrubayka** [comment]
Found an extensive guide that supports your Fix! You can link it next time for anyone who has troubles with setting up DS4.

http://mgsforums.com/topic/9029014/1/

**Comment by vrubayka** [comment]
Sorry for posting so much, I was celebrating too early, I think this guide was made with the older version of the fix in mind and now it doesn't work. Oh well... I'll keep trying

**Comment by VFansss** [comment]
I was pretty sure I had answered, but I was serious wrong. I'm sorry 😕 

The last build of the fix could have solved the issues. Also, I'm going to update the Wiki's page about Controls & gamepads to better explain how the DS4 is working!

**Comment by vrubayka** [comment]
@VFansss Hello, I've decided to test the game out one more time and I've discovered that I can't release the weapon while aiming (keep LS pressed and release Fire), Snake still shoots the gun. So I went to the config files and checked them out and found out that two Input variables are set to the same index. I think these are the stick buttons, correct? Maybe the inputs overwrite one another during gameplay? Can you check that out? This is Xbox setting + PS2 layout btw.
![padbtn_xbox_ps2layout](https://user-images.githubusercontent.com/35918204/76794353-1e233c80-67c7-11ea-96eb-3b565a6e08e1.png)
![padbtns_xbox_ps2layout](https://user-images.githubusercontent.com/35918204/76794355-1ebbd300-67c7-11ea-804e-2e8706a0e160.png)

**Comment by vrubayka** [comment]
Here's Xbox pad + V's Layout, no conflicting inputs
![image](https://user-images.githubusercontent.com/35918204/76794664-c76a3280-67c7-11ea-95e1-57a8acf15b28.png)
![image](https://user-images.githubusercontent.com/35918204/76794674-d05b0400-67c7-11ea-8ef6-00c17345a0ff.png)

**Comment by vrubayka** [comment]
@VFansss 
Hey do you know anything about those indices for L3/R3 inputs i mentioned above?

**Comment by VFansss** [comment]
Sorry for the none-answer.

The "confict" you mentioned above is perfectly normal, and works as intented. They are 2 different special actions bound to the same button. Nothing strange.

My advice could be to download [Xinput plus](https://sites.google.com/site/0dd14lab/xinput-plus) (first link in blue from above), extract the archive in a location that ISN'T inside the game location, open the software and then open the "mgs2_sse.exe" and read the xinput plus config made by the fix.

You can see the gamepad reading from inside the software, in the test section.

Check if R3/L3 is working good.

Aside that: what kind of DS4 do you have? I'm testing the game using an original DS4, and everything seems to working good. Are you using any kind of external software to make it working?
