### ISSUE TITLE
Unable to open MGS2SSEtup.exe

### ISSUE THREAD

**Issue by cnnrmcnl** [VFansss/mgs2-v-s-fix#46]
Keep getting an error message, I've attached the debug text file that it generated.
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2247851/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
Are you using the 1.04 version of the fix, right?

If so, try to start the Fix (MGS2SSetup.exe) using admin right. How? Press the right mouse button on the file, and select ' Run as administrator'

**Comment by cnnrmcnl** [comment]
Tried doing a clean install with version 1.04, also tried running the file as an admin. Seems like I'm getting the same debug error.
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2250002/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
The issue isn't 100% related to the fix itself: it seems that you can't get enough elevated right to write inside the main game folder.

You disabled the Windows [UAC](https://en.wikipedia.org/wiki/User_Account_Control)? If yes, you can try to re-enable it and try again to start the fix using admin rights. A windows should pop up, and you can grant privileges.

A more complicated way is to make the whole 'bin' folder to be writeable by all users. You can do it selecting the 'bin' folder with right mouse click -> properties -> Security -> (In the middle of the window) Edit -> (On the top list) select ' Users' -> (On the bottom list) select 'Complete control'

A third way would be to manually apply the path: download [THIS](https://github.com/VFansss/mgs2-v-s-fix/blob/master/mgs2%20v's%20fix/Resources/3_fixed_exe.zip), and extract its content inside the 'bin' folder. Then (inside the same bin folder) create a file called "_fixed_exe_applied.sss" (without quotes).

**Comment by cnnrmcnl** [comment]
Tried your third solution, it worked immediately. Thanks for the help, I really appreciate it!

**Comment by VFansss** [comment]
I'm glad it worked!

Happy playing! :)
