### ISSUE TITLE
R1/L1 not working

### ISSUE THREAD

**Issue by hankyuller** [VFansss/mgs2-v-s-fix#5]
First of all, thanks for the fix ! And then I ran into an issue with controller support. Triggers are working as intended, only there is no R1/L1 at all.

I'm using a xbox one controller, but it shouldn't make a difference isn't it ?

**Comment by VFansss** [comment]
Watch out: R1/L1 do only some context special action, like aim without fire, parry with sword ecc. Try to press L1 on the main menu: if you don't ear some gunshot/thunder well...it doesn't work.

Tried to reinstall?
Enabled 360 gamepad on Control menu tab?
Can you post me your padbtn.ini (you can find it inside .exe directory) here or on pastebin?

One controller should work like 360, so it's very strange...

**Comment by hankyuller** [comment]
Yes I can make the gunshot in the mainmenu and also the 360 gamepad is enabled.

here is padbtn.ini :
> 00  A
> 01  B
> 02  X
> 03  Y
> 04  L2
> 05  EX3
> 05  AR
> 06  SEL
> 07  STA
> 08  EX2
> 09  EX1
> 0A  L1
> 0B  R1

**Comment by VFansss** [comment]
Ini is ok. So seem that all it's working good...

L1/R1 are used only in few context. 
You can hold R1 to aim without fire with M4/ak, hold L1 to walk during aiming and both are used for Katana. They are used even for other minor actions...

Unfortunately the layout isn't 100% similar to the ps2 or HD Remaster ones. It's the best one that allow you to do all actions without having to use external and not-freeware mapping tool (like xpadder).

Sorry for that :p
