### ISSUE TITLE
Whenever I try to replace the MGS2Setup Avira keeps warning me and it disappears out of my folder path  

### ISSUE THREAD

**Issue by Alphaw0lfxc** [VFansss/mgs2-v-s-fix#53]

**Comment by Alphaw0lfxc** [comment]
Avira doesn't fuck me over when I use 1.5 but when I use 1.6 Avira will start getting salty

**Comment by VFansss** [comment]
I can understand that some anti-virus could detect something strange going on (albeit, obviously, the fix doesn't contain nothing bad), but it's truly strange that the 1.5 version is working but the 1.6 is getting flagged for something strange.

From 1.5 to 1.6 I didn't changed a lot of things: the WindowsXP compatibility and the Dx8toDx9 wrapper is on by default, and some minor things that I don't think will ever trigger anything.

I don't use Avira, so I can guide you to do that, but could you please tell me why Avira think the software is something dangerous?

For sure you can check your anti virus "quarantine" and check why it got removed.

For the next version I will send the fix to Microsoft to add it to the trusted .exe list, and this in cascade will make it more "trustable" by antivirus. Or at least I hope that.

**Comment by VFansss** [comment]
There are actually 2 good working solution:

* Pay €100 each year to buy a digital signature to sign the fix executable.

* Warn the user about that the things above could happen (And I've done it editing the V's Wiki), release the source code so anyone could understand that the wiki isn't doing anything harmful (And I've done it almost 2 years ago), and send the .exe to Microsoft with the developer program so maybe (and I say **MAYBE**) in the future Windows Defender and other Anti-Virus will know that they are working with a simple game fix and not with the work malware in the history of computers.

I've choose the latter option. Guess why 😄
