### ISSUE TITLE
Turning off Windowed mode results in "Failed creating Direct3DDevice8 Object"

### ISSUE THREAD

**Issue by elzafir** [VFansss/mgs2-v-s-fix#55]
So, I installed the Metal Gear Solid 2 Substance from Original ISO and applied V's fix.

Whenever I tried turning Windowed Mode to OFF, I am greeted with "_Failed creating Direct3DDevice8 Object"_ prompt. Any solution to this?

My WORKING settings is as follows:

> **RESOLUTION**
> Resolution (Auto detected): 1459 x 821
> Maintain Aspect Ratio: ON
> Full Screen Cutscenes: ON
> Optimized 16:9 FOV: ON
> Windowed Mode: ON
> Graphics Adapter (Auto detected): NVIDIA GeForce GTX 1050 Ti
>
> **CONTROLS**
> Controller: XBOX (DualShock 4 using DS4Windows; 'Hide PS4 Controller' ticked)
> Button Layout: PS2 Type
> 
> **GRAPHICS**
> Rendering Size: HIGH
> Shadow Detail: HIGH
> Model Quality: HIGH (or MEDIUM)
> Rendering Clearness: HIGH
> Effect Quantity: HIGH
> Anti Aliasing (SMAA): OFF (or ON)
> Extra Cool Effects: ON
> Motion Blur: ON 
> 
> **OTHER**
> Open V's Fix after playing: ON
> Sound Quality: 44khz
> Sound Effect Quality: HIGH
> 3D Sound Quality: HIGH

My system:
CPU: AMD Athlon II X4 640 3.0GHz Quad-Core
RAM: 8GB DDR3
GPU: NVIDIA GeForce GTX 1050 Ti 4GB DDR5
OS: Windows 10 Pro (Version 1803, build 17134.285)
GPU Drivers: NVIDIA GeForce Game Ready Driver 411.70 - WHQL (Sep 27, 2018)

I don't have SweetFX separately installed.

**Comment by VFansss** [comment]
Sorry for the late reply!

Before all: thanks for writing me your system configuration, but in much more effective to let the [DEBUG MODE](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) do its works. Please send me the debug .txt file and the last.log.

> Whenever I tried turning Windowed Mode to OFF

By default, windowed mode is configured to OFF, so the game never worked in the first instance?

**Comment by CookiePLMonster** [comment]
> Is a pretty strange resolution...what monitor do you have??

I have seen this happen (weird resolutions, that is) to people who use DPI scaling - while I have never reproduced it myself (even with scaling), it may be related to that.

**Comment by VFansss** [comment]
I'm pretty sure that the error show up because DirectX try to render the game in fullscreen with that phenomenal weird resolution (that I don't even think is physically existing on a monitor).

Activating "Windowed mode" made the game working because a window can be created with whatever resolution, even if it doesn't fit the screen.

The interesting fact is: why the fix has auto-detected that resolution? Maybe something in the auto-detect algorithm is wrong? What is the true native resolution of the monitor?

**Comment by VFansss** [comment]
Well, I'm pretty sure that the issue above was caused by an truly out-of-range resolution for DirectX8.

Until further reports, I'm pretty confident that using a better supported full screen resolution will solve the issue 😄
