### ISSUE TITLE
Graphical problem during final credits

### ISSUE THREAD

**Issue by Neo941** [VFansss/mgs2-v-s-fix#57]
Hi,

I contact you to report a graphic problem during credits. 
This problem has impeded me to view a part of the screen.
Any suggest?

**Comment by Neo941** [comment]
Yes, it's about the plant chapter.
To be precise, the problem is that some portion of visible movies during the credits (ex. that with lady liberty) are permanent and the result is the overlay of this latter on the screen.

**Comment by Neo941** [comment]
Unfortunately I don't have any screenshot.

**Comment by VFansss** [comment]
I don't ask you to send me a screenshot, so I will try to replicate the bug on my system, albeit I never saw it in any of my playthrough.

It can also be a codec issues, so it would worth the time to install the [Klite codec pack, like I've sayed on the "common issues" page](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#common-problems--common-solutions).

**Comment by Neo941** [comment]
The Klite codec pack was already installed when I noticed the problem.

**Comment by Neo941** [comment]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2476605/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
I will keep an eye on it...

Thanks for reporting it 😄

**Comment by VFansss** [comment]
Didn't found anything useful to cope with that.

Without any video, screenshot or something like that I can't figure out what went wrong.

A kinda failure on my part.
