### ISSUE TITLE
Widescreen fix was updated

### ISSUE THREAD

**Issue by Keith94** [VFansss/mgs2-v-s-fix#6]
http://ps2wide.net/changelog.html

* 25.02.2017: updated FMV's fix in widescreen patch for PC verison of [Metal Gear Solid 2: Substance ](http://ps2wide.net/pc.html#mgs2)

**Comment by Keith94** [comment]
Also, the updated fix may support all aspect ratios (21:9, etc.) since it's no longer written in the .ini file.

**Comment by VFansss** [comment]
Before all: THANKS for reporting it!
I would never have seen without you.

Now I had enough time to try it.
I've tried it hoping for green screen fix on Tanker chapter, but I don't seen any difference.
I've send an email to the author asking for explanation, thus I've understand: Now the "movie box" inside VR Mission is displayed properly, and is not anymore stretched.

A nice cool addiction.

Also is true that now it's working on any kind of resolution ratio.
But unfortunatelly if the resolution isn't 16:9 or 16:10 the subtitle (ingame and codec ones) are displayed shifted to left, making them kinda odd. This doesn't happen if the resolution is set to previously written resolution.

I don't know if it's a simple oversight or is intended. I warned the author, hoping for a proper fix.

I've send a mail to some other people asking for help fixing resolution lock and green screen problem. Also I want to try to include AntiMicro and analogic button support (for ps2 real gamepad and ps3 sixaxis), but now I'm busy with other project so probably this will require quite some time.

**Comment by Keith94** [comment]
Thanks for testing, keep us updated on what you find. :)

**Comment by Keith94** [comment]
Btw, new version from today added custom FOV option.

**Comment by VFansss** [comment]
Yup, I keep in touch with nemesis2000. I'm sure the fix is going to be update in the next days/week, so I think I'm going to let some time pass...

I'm trying to solve some other problem that some user has reported me, than I will include it!

Thanks for reporting me, through!
