### ISSUE TITLE
Savedata folders bug + Failed creating Direct3DDevice8 Object

### ISSUE THREAD

**Issue by TuxNews** [VFansss/mgs2-v-s-fix#68]
At opening....

**Comment by VFansss** [comment]
Hi!

I've just released a new version (the 1.7) with a lot of changes. Please can you try that and check if the situation is solved?

Also, please read the [Debug mode](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) tutorial and send me the file on your desktop!

**Comment by TuxNews** [comment]
Same error with 1.7. Here's the file
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2728105/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
Maybe is due to the strange resolution that isn't compatible with the game.

Can you please try to manually set the resolution to 1920*1080 and try again?

**Comment by TuxNews** [comment]
@VFansss Uh i started it in FULL HD, and ti started. But with no audio, so i closed it, checked MGS2SSetup.exe Settings and....it doesn't work anymore. It just display this and close:
![bbbbb](https://user-images.githubusercontent.com/45686773/50705038-bcf7c900-1059-11e9-9dd8-37d32dadac38.png)

**Comment by VFansss** [comment]
Just press 'OK' and send me again the debug file you can find on your desktop

**Comment by TuxNews** [comment]
@VFansss 
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2728141/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
Seems that there is enabled some kind of DPI Aware that is making the fix go crazy.

![immagine](https://user-images.githubusercontent.com/15073502/50705671-d3068900-105b-11e9-9db6-1d2ab820245c.jpg)

Can you disable it?

Also, please be sure to start the fix with admin rights (right click on it -> Start with admin rights), because I think that something 

![pic2](https://user-images.githubusercontent.com/15073502/50705742-119c4380-105c-11e9-89e6-dcbc48d22d29.JPG)

**Comment by TuxNews** [comment]
@VFansss DPI Options are all disabled...and yes, i started as administrator but nothing.

**Comment by Loggan08** [comment]
Try installing this one

https://www.microsoft.com/en-us/download/details.aspx?id=9155

**Comment by VFansss** [comment]
Can you try (just to understand) the older version (1.6) you can [find here](https://github.com/VFansss/mgs2-v-s-fix/releases/download/v1.6/MGS.V.s.Fix.v1.6.zip), obviously setting 1920*1080 like we previously told? (That's because game doesn't start with very...weird resolution, [like I've saw in the past](https://github.com/VFansss/mgs2-v-s-fix/issues/55) )

If the fix detect some HIGHDPIAWARE mean that...that option exist!

Just to understand: if you press 'OK' on that error and you press SAVE...what happen?

Can you please do it and then send me again the log?

> @VFansss DPI Options are all disabled...and yes, i started as administrator but nothing, same error.
> 
> Non ho flag per DPI elevati attivate, né opzioni di ridimensionamento testo nelle opzioni schermo di Windows, non capisco perché nel log risulti, forse devo disattivarlo direttamente tramite registro?

Eh, non parlo in italiano perchè poi gli altri non capiscono, non per altro. A volte ci azzeccano meglio di me...

**Comment by TuxNews** [comment]
@VFansss 
I can't press SAVE, because after "ok" it just close. I deleted that key on regedit, but nothing changed, same error. I'll try with 1.6 now, lets see.

**Comment by VFansss** [comment]
Ok. I've updated some things.

Please redownload the 1.7 version of the fix, and try again.

This time it should work without issues. Please tell me if something isn't working as intended.

**Comment by TuxNews** [comment]
@VFansss Ok, new 1.7 works. Nice. Finally i can play again at the best Metal Gear of all times.

**Comment by VFansss** [comment]
Grandeee 👍 

Just a last thing: did you done something to fix the "missing audio" issue? You installed the redist Logan posted above? You changed something or you followed something inside the Fix Wiki?

Is important to avoid the issue if it show up again...

**Comment by TuxNews** [comment]
@VFansss Was my fault, i had the speakers plugged-in instead of the headphones....lol. Software-side, about audio, it's everything perfect. In 1.6 and 1.7.

**Comment by TuxNews** [comment]
@VFansss i think there's a bug with save folder. My save folder its inside H:-->Giochi installati-->Metal gear ecc-->savedata, but the game create another saving folder on Documenti-->Mygames. 

When i try to open the launcher with a save data in one of the two folders, this message appear:
![cccc](https://user-images.githubusercontent.com/45686773/50712768-f8eb5800-1072-11e9-9815-69470605e14e.png)

**Comment by VFansss** [comment]
Please delete both folders, start your game and make new game (tanker or plant is not important), then save your game and please check what folder actually contain something.

I know is annoying, but this way I can pinpoint the issue...

**Comment by LobizonXP** [comment]
I've had the same issue. Deleted both of the directories, but v1.7 patching wasn't working after failing, so the savedata used by the game was still inside the game folder.
Made a clean install of the original game and patched fresh with 1.7. That worked ok, and now the saves are stored inside "My Games".

**Comment by TuxNews** [comment]
@VFansss Done. Well, it recreates the folder inside H-->ecc but, if i reopen the launcher, it show the same problem of the two folders, recreating automatically the folder inside C-->Documents-->MyGames.

**Comment by TuxNews** [comment]
@VFansss @LobizonXP Yep, fresh install solved everything. Now save folder creates on C-->ecc. and launcher dont recreate it on H. Perfect.

**Comment by VFansss** [comment]
I think I've understood the issue (more...or less), but I need to do some fiddling to make it working like it should.

I've already tested the "Move savegame to new location" moooore than once, but my latest bugfix for the issue that Tux has posted (for the right reason, obviously) has broken the fix logic on how to cope with existing savedata (or, at least, with the existing "savedata" folder inside the game folder itself).

Now I'm really tired 😴 but I need to do some deep test on how to solve this without reinstalling the game (like it should and like I've designed that).

For now, I have to "nuke" the 1.7 version of the fix, at least until tomorrow.

I'm sorry for the wasted time on this very silly thing, but I've tried the fix on several different configs and...well, things like that happen anyway.

Thanks for the patience, I will update this soon...

**Comment by TuxNews** [comment]
@VFansss Sorry for contacting you here, but i don't know in wich way i can. I remapped the keyboard input file (kb.ini), it's a lot more easier playing the game in this way (at least, for me), maybe you can add it as an optional file on Github or add the keys to the existing one. **Standard PC controls are completely garbage, nice work Konami**.

It's a reworked way for those, like me, who are used to play at recent games with mouse and the classic movement layout (w front, a left etc). So, instead of mouse, i set the numpad (to have a certain space for the right arm) with some commands (8 to see in front of you, 4 as x to aim and shoot). I find it really comfortable. Maybe i'll change crouch  to "RIGHT" or "+" keys, because it's comfortable.

Let me see what you think (and maybe let me know how to contact you, an email, something, probably i'll propose other modifications).
[kb.zip](https://github.com/VFansss/mgs2-v-s-fix/files/2729666/kb.zip)

**Comment by VFansss** [comment]
> 
> 
> @VFansss Sorry for contacting you here, but i don't know in wich way i can. I remapped the keyboard input file (kb.ini), it's a lot more easier playing the game in this way (at least, for me), maybe you can add it as an optional file on Github or add the keys to the existing one. **Standard PC controls are completely garbage, nice work Konami**.
> 
> It's a reworked way for those, like me, who are used to play at recent games with mouse and the classic movement layout (w front, a left etc). So, instead of mouse, i set the numpad (to have a certain space for the right arm) with some commands (8 to see in front of you, 4 as x to aim and shoot). I find it really comfortable. Maybe i'll change crouch to "RIGHT" or "+" keys, because it's comfortable.
> 
> Let me see what you think (and maybe let me know how to contact you, an email, something, probably i'll propose other modifications).
> [kb.zip](https://github.com/VFansss/mgs2-v-s-fix/files/2729666/kb.zip)

I've moved this on a separate issue here ---> #71

**Comment by omakiller45** [comment]
I noticed that when I try to play this game at a 4K resolution I get the Failed to create direct3Ddevice object 8 error, but I used to have no problem rendering the game at a 3480x2160 resolution. Just thought I would report just in case.

**Comment by VFansss** [comment]
The new 1.7.1 release should have solved this nasty bug once for all.
