### ISSUE TITLE
Fullscreen cutscenes show effects and geometry that shouldn't be visible

### ISSUE THREAD

**Issue by ahemfck** [VFansss/mgs2-v-s-fix#72]
![mgs2_sse screenshot 2019 01 10 - 10 53 59 48](https://user-images.githubusercontent.com/45542721/50957571-357de000-14c7-11e9-8d6b-7bbc49633c9a.png)
![mgs2_sse screenshot 2019 01 10 - 10 57 06 64](https://user-images.githubusercontent.com/45542721/50957575-39116700-14c7-11e9-8569-be32ebb454d5.png)
![mgs2_sse screenshot 2019 01 10 - 10 59 12 21](https://user-images.githubusercontent.com/45542721/50957578-3b73c100-14c7-11e9-8729-d897b42b500f.png)
![mgs2_sse screenshot 2019 01 10 - 11 21 23 43](https://user-images.githubusercontent.com/45542721/50958740-15035500-14ca-11e9-823c-b2b7cbedd0fa.png)

although i don't know how this works i was thinking a viable solution to this would be zooming in when the effect or texture is present on the screen or in general just zoom in to all of the cutscenes
another solution could be to remove these specific effects for the time being(the binoculars could benefit since the blackbars around it don't give anything only the text needs to be present)

**Comment by UltimateNova1203** [comment]
From my own research, i can add to this somewhat. Nemesis' widescreen patch doesn't affect the cutscenes (or at least based on how it modifies the in-game camera/what i have noticed). You can add black bars in the mgs2w.ini file in the ./bin/scripts/ folder to offset this somewhat. If you want an even worse example, in the Plant, after the Fatman fight, watch the cutscenes for the Ninja meeting. When it shows the side of Strut-E, near the end of the codec calls, there is a big part that is chopped and it looks bad.

As for items like the binocular texture (and the Skull Suit scene), the part that isn't covered is a part of the texture itself. You can modify the texture to fill that part, but then the texture management becomes a PITA to handle (I've been modifying the textures for a "HD Pack", and it's not fun). I haven't messed with this part of textures yet, but i believe the texture will stretch to fill the viewport, with the black bars edited in the mgs2w.ini file adding padding so you wouldn't see it. This will require more testing though. Let me find the camera texture and I can explain how it works further.

If you give me some time, i can dig further into this and find exactly how the game handles these scenes with the textures with the black bars in that INI file. I already know that the camera and skull suit is handled by textures, but I am unsure about the Olga scene. Try playing around with the black bars. I personally like to set 480 on the top and 360 on the bottom, as it's close to the same height for both bars (for that cinematic experience), this is on 1920x1080.

**Comment by VFansss** [comment]
I missed the GitHub notification, so sorry for the late reply 😭 

Aside for your suggested solutions, the things you have said aren't so easy to do, if not simply currently impossible :/

The "black bar removing" was a little an fun extra, but isn't intended to work perfectly in every situation. Currently fixing that is far out my competence field, but both solution you have posted have some tradeoff that make them equally a not perfect solution.

The best things would be to play with reduced black bar size  (is configurable inside the .ini file) but again is another tradeoff, so I don't think a perfect solution exist right now.
