### ISSUE TITLE
Failed creating Direct3Ddevice8 object error when attempting to launch the game at a 3840x2160 resolution.

### ISSUE THREAD

**Issue by omakiller45** [VFansss/mgs2-v-s-fix#74]

**Comment by VFansss** [comment]
Hi! Can you please read [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) and send me the debug file written there?

**Comment by omakiller45** [comment]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2780292/MGS2_VFix_debug.txt)

Here you go @VFansss hopefully this will help!

**Comment by VFansss** [comment]
Good!

But you didn't done what I've wrote on the wiki!

> When fix is open, press 'SETTINGS' and then 'SAVE', and the fix will log a lot of useful things inside a .txt file called MGS2_VFix_debug.txt, that you can find on your desktop.

The log doesn't contain anything useful. Please send it again with the required info!

**Comment by omakiller45** [comment]
Oops my sorry about that this should be good.
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2788954/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
I don't have a 4k monitor myself, but from the log I can see that you have set a 3**48**0x2160 resolution, but I probably bet that your monitor resolution is 3**84**0 x 2160.

8 and 4 are switched in place.

Try to put a valid resolution and try again.

Tell me is it has worked 😄

**Comment by omakiller45** [comment]
Oh my gosh, I can't believe I got the numbers mixed up...
