### ISSUE TITLE
Music/Voices Gone Permanently 

### ISSUE THREAD

**Issue by epicoolguy** [VFansss/mgs2-v-s-fix#8]
So I beat Tanker-Plant on Normal and things worked the entire time. When I booted up the game again later to play the VR missions, the music and voices had all gone. I tried to play Snake Tales and Tanker-Plant on Hard, but the voices and music remained gone. I changed the audio settings around to different configs but nothing would make it work. I'm running Laptop Mode if that makes a difference. Still, thank you so much for the fix! It worked perfectly up until now.

**Comment by VFansss** [comment]
What a strange thing :/

Open the game; in the main menu go to "OPTION" and see if SE and Music is set to 15 (= the max). The game has a bug (that I really don't know how to fix) that if you play on Very Easy on certain occasion it will set automatically both these option to 0. Is present on the original game, so it's not V's Fix fault and it's kinda impossible to solve :/

I don't think this is the case, but worth a look...

Other than that I don't wanna sound rude but...try to disinstall the game, clear the 'bin' folder of the game and re-install all from scratch. It's a PC so ehi: who knows what can go wrong :exclamation: 

If you want you can send me the content of mgs2.ini, but I don't think there is something out of place.

Let me know if it work. If is not we can try something more...imaginative :boom:

**Comment by epicoolguy** [comment]
Thanks, I'll try a reinstall right now and keep you updated. Thanks for your help!

**Comment by epicoolguy** [comment]
Update: Tried a fresh reinstall and the problem wasn't fixed. I'm gonna try to reinstall again without the fix to see if it works but I'll keep you updated.
