### ISSUE TITLE
Enhance keyboard controls

### ISSUE THREAD

**Issue by CiaranZagami** [VFansss/mgs2-v-s-fix#81]
I have no way to make right stick inputs which means I cannot use the sword in anyway. I've tried every single key on the keyboard
Therefore I cannot attack the final boss at all as the sword is the only weapon you have during that fight

**Comment by VFansss** [comment]
Hi!

Try [THIS](https://github.com/VFansss/mgs2-v-s-fix/issues/71) keyboard layout!

Download it, and extract it inside the 'bin' game folder.

**Comment by CiaranZagami** [comment]
Thank you so much!
I have to relearn the controlls now but at least I can use the sword!

**Comment by VFansss** [comment]
Unfortunately I never focused on the mouse+keyboard playing.

My plan was to make a complete and personalizable keyboard setupper but realizing that is too much time consuming and I don't know if I will ever do that, but for sure I could include some various keyboard layouts...

I will consider that for the next release, thanks for reminding me that!

**Comment by CiaranZagami** [comment]
I completely understand why and I accept that the game is best played with a controller.
Its simply that I can't really afford a quality controler and even if I could this is the only game I'd use it for and I'm not sure it justifies the buy.

But thank you very much for having the time to help a complete outlair like myself!

**Comment by VFansss** [comment]
I've noted that, with the default layout, the katana can be used with I-J-K-L buttons.

[I've edited the wiki with more info on the topic!](https://github.com/VFansss/mgs2-v-s-fix/wiki/Controllers-&-Actions#menu)

I think is much more complete to put everything inside a single page!

I hope you had fun playing the game.
