### ISSUE TITLE
MGS2SSetup.exe Can't Move Save Games Across Volumes

### ISSUE THREAD

**Issue by Platzkart** [VFansss/mgs2-v-s-fix#82]
Hi, I just updated to 1.7.1. Despite my MGS2 folder being in D:/Games, trying to save my settings resulted in a fatal UAC error. After running in debug, I realised that this is because the .exe is unable to move my save files across volumes (or to create a fresh folder in a different volume, which I also tried after deleting my old saves).

The relevant portion of my debug file is:
[MOVE SAVEGAME TO NEW LOCATION] Method starting...
06.42.53.459 -> [MOVE SAVEGAME TO NEW LOCATION] old: D:\Games\MGS2\savedata | new: C:\Users\Platzkart\Documents\My Games\METAL GEAR SOLID 2 SUBSTANCE
06.42.53.460 -> [ EXCEPTION ] Source and destination path must have identical roots. Move will not work across volumes.
06.42.54.737 -> [!] Showed a messagebox with code: UAC_error

**Comment by VFansss** [comment]
I wasn't very fast (pretty busy lately) but I can say it officially: **it's solved in the last release!**

Thanks for reporting me that: I would never have noticed it on my own: it was a very pesky bug (and honestly a bad design choice for that Microsoft function. But in the end... what do I know? 😬 )

Thanks ❤️
