### ISSUE TITLE
My MGS2Setup problem...

### ISSUE THREAD

**Issue by fazrigading** [VFansss/mgs2-v-s-fix#83]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3020687/MGS2_VFix_debug.txt)

Please fix it...

**Comment by VFansss** [comment]
Hi!

From the log, I can that you are suffering a known bug.

[Another user has already reported it, so you can simply follow what I've written there.](https://github.com/VFansss/mgs2-v-s-fix/issues/82)

I'm sorry for the issue: I should fix it as soon as I can 😬

**Comment by VFansss** [comment]
I've released a new release, that will automatically address the issue.

Thanks for the patience!
