### ISSUE TITLE
Problem starting up mgs2

### ISSUE THREAD

**Issue by Importedgame2009** [VFansss/mgs2-v-s-fix#87]
After i reset my computer it wont open i see it in the taskbar then it just closes any ideas? And im using the original dvd i tried reinstalling  the problem is still there am i missing any microsoft visual files? If so what are the ones needed and it also said specified module not found and after that abnormal shutdown. when i tried installing the net but it says i have a higher one do i have to uninstall the higher one and install that one?

**Comment by Importedgame2009** [comment]
Please help i really want to play it again

**Comment by Importedgame2009** [comment]
Its saying specified module not found any fix?

**Comment by VFansss** [comment]
If you want to add something to your message, don't post more than once, and use the EDIT function.

If your just reinstalled your operative system, probably you are missing .NET 4.5.

Please read [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#requirements) chapter of the guide. You can find a download link for it.

If it doesn't work, please [activate DEBUG MODE](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) and send me the file you will find on your desktop.

**Comment by Importedgame2009** [comment]
I have reset my system

**Comment by Importedgame2009** [comment]
So il try installing it and see if it works

**Comment by Importedgame2009** [comment]
ok il start editing my comment instead

**Comment by VFansss** [comment]
From what I can read from the other issue, I think you figured out how to start it up.

I'm closing here...
