### ISSUE TITLE
Cutscenes go blackscreen and crash

### ISSUE THREAD

**Issue by lDan89l** [VFansss/mgs2-v-s-fix#88]
Hello,

here are my problems:

1) I can't see the intro cutscene, I just see black screen with the audio in background. I can't skip it even if I press buttons (seems a pretty classic issue)

2) The problem above happens sometimes also to cutscenes during the games. Again, when it happens I can't skip the cutscenes. Sometimes I am able to skip the video in a preventive way (pressing very fast buttons X or START).

3) Sometimes (usually when there are several cutscenes which goes blackscreen), there is a single cutscene which make the game crash. This is the case of a cutscene which I should see after the President is death...I can't skip it and and I am stucked here, since it alway crashes.
I met other cutscenes that made my game crash in the past, but I managed to skip them in a way or another (or, other times, they just functioned properly when a tried 2nd time).

What I did (and didn't work):
- Installed K-Lite Version 14.9.4 Standard ~ 39.4 MB ~ May 4th 2019  K-Lite_Codec_Pack_1494_Basic.exe. Do I have to do something specific, after installing it?
- Disabled mpegvideo format in LAV Splitter Configuration program.
![image](https://user-images.githubusercontent.com/50252870/57573600-7e6c8380-742a-11e9-8f77-7ba37df26a27.png)

My configuration: [MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3169352/MGS2_VFix_debug.txt)

Any idea?

PS: here is my game saving, could anyone play it just after the cutscenes with snake and otacon and give me a new playable save to me? :D
[Sfj0grWnCTG4gh1gdMmZ6z9VoPkjOuv03FNoJ.zip](https://github.com/VFansss/mgs2-v-s-fix/files/3169375/Sfj0grWnCTG4gh1gdMmZ6z9VoPkjOuv03FNoJ.zip)

**Comment by VFansss** [comment]
Sorry for the very LATE reply. I was sick these days, and then...I simply forgot.

My apologies...

> I can't skip it even if I press buttons (**seems a pretty classic issue**)

Why you tell is a "classic issue"?

No one has ever reported me something similar, neither I experienced it in first person...

Aside that, the issues 2 and 3 make me thing that something is VERY wrong here...

Can you please try to re-install the game to another location?

Another worthy test would be to lower graphics, deactivate anti-aliasing and/or deactivate widescreen fix ("Optimized FOV in the fix settings")

> here is my game saving, could anyone play it just after the cutscenes with snake and otacon and give me a new playable save to me? :D

I would do it, but I found that this situation is SO weird that worth trying to solve it, instead to let the game broken and free to crash for things that should work perfectly out of the box 😢

**Comment by lDan89l** [comment]
It's really weird. Neither lowering graphics nor reinstalling to another location works.
Fix version seems to be a factor.

With version 1.6 I have the situation described in the post.

With version 1.7.2:
- The intro cutscene crashes, unless I press X/START before it starts (while with version 1.6 it doesn't crush but only goes blackscreen)
- In general, cutscenes that were blackscreen in version 1.6 crash with version 1.7.2

But, if I start the game from the file mgs2_sse, I don't have the issues of version 1.7.2 but just the issues of version 1.6.

I don't know how, but after the various tries I managed to skip the part where I was blocked....But I'm now blocked to another cutscenes, where it keeps crashing -.-

**Comment by VFansss** [comment]
> But, if I start the game from the file mgs2_sse, I don't have the issues of version 1.7.2 but just the issues of version 1.6.

I will explain you the why of this strange behaviour:

With 1.7.2, if you start the game directly from mgs2_sse.exe, the game start without admin rights (because it doesn't need it anymore: this is as intended improvement, and has been inserted from 1.7 and above).

If, in both 1.6 and 1.7, you start the game from the V's Fix, the game start with admin rights.

The fact that you have these incompatibility in both version, and the crash reasons change when the game is stated with different rights make me think that you have some privileges messed up on your system on the game folder.

Please can you provide me a screenshot like El-Hack done in [THIS](https://github.com/VFansss/mgs2-v-s-fix/issues/41) issue?

**Comment by lDan89l** [comment]
Here it is:

![image](https://user-images.githubusercontent.com/50252870/58041862-7783f600-7b39-11e9-817c-0be5270cf3d9.png)

**Comment by lDan89l** [comment]
up

**Comment by VFansss** [comment]
I'm truly sorry for the late reply, but I can't truly correctly word how busy and tired I'm lately. I hope you didn't give up.

Here's an explicit image on what you should do:

![immagine](https://user-images.githubusercontent.com/15073502/59089420-5b8a9d80-890a-11e9-99d8-0fb1dcbb3a26.png)


The start the game from mgs2_sse.exe

**Comment by lDan89l** [comment]
Thanks, but it didn't work. :(

 I have the same problems (blackscreen intro, and random cutscenes crashing)  starting the game from MGS2SSetup.exe or from mgs2_sse.exe

**Comment by VFansss** [comment]
Have you tried to use a different graphic adapter?

Also: can you try to install again the game inside another directory?

Il dom 9 giu 2019, 13:07 lDan89l <notifications@github.com> ha scritto:

**Comment by lDan89l** [comment]
I already tried different directories, to no avail. For the graphic adapter, I have only 1 (my internal Intel Graphics)

I don't know if it matters, but I tried applying the security rights not only to the bin folder, but to the whole MGS2 folder, and it gave me this error:

![image](https://user-images.githubusercontent.com/50252870/59158273-e9f05200-8ab7-11e9-9abe-6f1a839813c0.png)

**Comment by VFansss** [comment]
For sure is something VERY strange.

Can you please try to reinstall the game to somewhere else, apply the security policy, THEN apply the fix and try to apply the security settings again?

The fact that you can't change the security policy is 100% related to the crash you are experiencing, and should be solved beforehand!

**Comment by lDan89l** [comment]
I should apply the security policy just to the bin folder or to the main folder?

**Comment by VFansss** [comment]
Do it to the main folder!

Il dom 9 giu 2019, 18:18 lDan89l <notifications@github.com> ha scritto:

**Comment by lDan89l** [comment]
Reinstalled the game, applied the security policy to the main folder (without errors), then applied the patch 1.7.2, then reapplied the security policy (without errors) but it gives the usual error: the intro crashes from MGS2SSetup.exe and goes blackscreeen from mgs2_sse.exe
-

**Comment by VFansss** [comment]
Ok, time to sort it out: new Issues suggested me that the cause of this may be the anti-aliasing and the model quality set to high at the same time.

I've added to the 'common problem & common solutions' wiki page.

The new upcoming version and the new things I've added to ['Downloading & installing the fix'](https://github.com/VFansss/mgs2-v-s-fix/wiki/Downloading-&-Installing#-unzipping-the-fix) maybe are enough to now face this issues never more
