### ISSUE TITLE
No anti ailasing ingame, even if is activated from the Fix

### ISSUE THREAD

**Issue by Importedgame2009** [VFansss/mgs2-v-s-fix#90]
Here are my logs.
[last.log](https://github.com/VFansss/mgs2-v-s-fix/files/3194231/last.log)
[log.log](https://github.com/VFansss/mgs2-v-s-fix/files/3194232/log.log)

i cant find the main log on my desktop did i do something wrong?

**Comment by Importedgame2009** [comment]
help theres no AA it looks bad without it

**Comment by VFansss** [comment]
**PLEASE DON'T MAKE MULTIPLE REPLIES IN A ROW**

Doing that will not increase the possibility I will figure out the issue, so is pretty useless overall. Also, it bomb me with email, and I hate to be email bombed 😀 

> There is no anti ailasing i clicked on smaa and it still does'nt have anti ailasing any fix?

[Activate the debug mode and send me the log](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode)

**Comment by VFansss** [comment]
Can I know how you solved the issue?

**Comment by Importedgame2009** [comment]
I solved it by changing anti ailasing setting to use the 3d application setting in the nvida control panel for some reason it was off. You can close this issue
