### ISSUE TITLE
Controller crash

### ISSUE THREAD

**Issue by Ikkakujuu22** [VFansss/mgs2-v-s-fix#91]
Heya. when i select a controller layout in the launcher the game crashes but when i don't select one it runs fine. thanks in advance

**Comment by VFansss** [comment]
[Please activate the debug mode and send me the log](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode)

**Comment by Ikkakujuu22** [comment]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3196894/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
You didn't done what I've wrote on the wiki.

Please read it carefully and do it again.

**Comment by Ikkakujuu22** [comment]
sorry to be a bother but i don't see the issue. can i have a clue?

**Comment by VFansss** [comment]
![immagine](https://user-images.githubusercontent.com/15073502/58037005-b19acb00-7b2c-11e9-9a90-20f851237d0f.png)

**Comment by Ikkakujuu22** [comment]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3200180/MGS2_VFix_debug.txt)

sorry and thank you

**Comment by VFansss** [comment]
Can I ask you why you closed the issue?
