### ISSUE TITLE
Access to mgs2_sse.exe is denied

### ISSUE THREAD

**Issue by braditude84** [VFansss/mgs2-v-s-fix#92]
I downloaded the MGS2 V fix earlier today. It worked for awhile then  when I came back to it later it said I couldnt open it anymore. Can't do a sh*t?? I will attach a copy of the report

[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3221819/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
From what I can read from the log, the fix doesn't recognize that the game executable has been patched, and can't do it because something (windows, probably) is blocking it.

Inside the 'bin' game folder, there is a file called "_fixed_exe_applied.sss"?

You started even once the game?

**Comment by VFansss** [comment]
Hi!

Do you have any news on this issues?

**Comment by braditude84** [comment]
Hi! Sorry for the late reply. Had some stuff going on.  It happened to be
an issue on my end.  Lol. Fixed and works beautifully now. Thank you for
the follow up.

**Comment by VFansss** [comment]
Well, would be fantastic to understand what it was the solution: it could be useful for those who are searching for a similar issue...

...but, in every case, I'm glad you solved.

Have fun 😄

**Comment by braditude84** [comment]
It was something to do with another mgs2 app or cheat engine. Once I
uninstalled and reinstalled,  it all worked out. Sorry I'm not close to my
PC to check it out.  I think it was 2 apps clashing due to me installing it
in the wrong places.  That and some minor compatibility issues that was
solved was a simple right click.

**Comment by VFansss** [comment]
Oooook,

The most important things is now all is working good.

Have fun 😄
