### ISSUE TITLE
Save Games not moved with 1.7.2, Still requires UAC

### ISSUE THREAD

**Issue by LethalPlacebo** [VFansss/mgs2-v-s-fix#95]
**Describe the bug**

Hey, I know I'm late to the party, but I just noticed that update 1.7.2 should move savedata to the "my games" folder, and should no longer require UAC every time the fix is opened. This doesn't happen for me. I don't get any errors, but my saves stay in the game directory. If I try to move them manually and create the "METAL GEAR SOLID 2 SUBSTANCE" folder in "my games" as outlined in another post, the game just doesn't read the saves until I move them back to the game directory. The fix also still requires UAC every time I start it. The game is installed on my D drive. 

Thanks in advance for your time.

**Information on your machine**

OS: Windows 10 Home 64-bit
Hardware: Intel i7 7700k, GeForce GTX 1080, 16GB DDR4 RAM, dual monitors
Link to V's Fix debug file: https://drive.google.com/file/d/1WyRWJg5I1sBy3O3QYSfDoCm1UvCZdyzy/view?usp=sharing

**Comment by VFansss** [comment]
Hi there!

To propertly do a debug, I need that you press 'Settings' and then 'Save', and only then the debug log would be valid.

Read better [THIS](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#how-to-correctly-use-it) part of the Wiki!

**Comment by LethalPlacebo** [comment]
I could have sworn I did that, I'm sorry!

Here's the proper debug file:

https://drive.google.com/file/d/1WyRWJg5I1sBy3O3QYSfDoCm1UvCZdyzy/view?usp=sharing

**Comment by VFansss** [comment]
Let's start in order:

> and should no longer require UAC every time the fix is opened.  The fix also still requires UAC every time I start it.

This is perfectly normal, and is intented.

The fix mean that the UAC shoudn't prompt anymore if you start the game directly from mgs2_sse.exe

>  I know I'm late to the party, but I just noticed that update 1.7.2 should move savedata to the "my games" folder, This doesn't happen for me. I don't get any errors, but my saves stay in the game directory. 

From what I can see from the log, is seems that the fix has actually moved the savegames into 'My games'. Isn't true?

> If I try to move them manually and create the "METAL GEAR SOLID 2 SUBSTANCE" folder in "my games" as outlined in another post, the game just doesn't read the saves until I move them back to the game directory. 

Check if this file exist: [GAME DIRECTORY]\bin\scripts\SavegameLocationChanger.asi

As a last resource, you could try to reinstall the game to another location: I think that windows has memorized some compatibility settings to apply on mgs2_sse.exe, and is overriding what the fix is telling it to do.

**Comment by LethalPlacebo** [comment]
> The fix mean that the UAC shoudn't prompt anymore if you start the game directly from mgs2_sse.exe

Oh, I see, sorry!

So, the fix does move my save games to My Games > METAL GEAR SOLID 2 SUBSTANCE, but the game still refuses to read them from there. Seems it still wants to read them from the game directory. I have checked for "SavegameLocationChanger.asi" and it is in the correct directory.

I'll try moving the install of the game itself and see if that fixes it.

**Comment by LethalPlacebo** [comment]
Sorry for the delay!

I can confirm that moving the game to my C drive did not fix the issue. Specifically I moved the install folder to the "My Documents" folder on my C drive.

**Comment by VFansss** [comment]
Sorry for the clarification, but have you **reinstalled** or just moved the folder?

Because is not actually the same. My advice is to delete the game, and do a fresh reinstall.

**Comment by LethalPlacebo** [comment]
Hi, I'm so sorry I haven't responded to this! Unfortunately I cannot find my discs to do a reinstall, so I'll just have to assume that your solution of reinstallation would work. Thanks for all your help!
