### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by bugo9870** [VFansss/mgs2-v-s-fix#97]
Hey, first I just wanted to thank you for this awsome fix for my favourite game.
Unfortunetly I cant launch the fix
I am running the game on a W10 pc.
I attached the debug.
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3555630/MGS2_VFix_debug.txt)
Thanks.

**Comment by VFansss** [comment]
Ehi there.

It seems that you have installed the game in:
'D:\נועם\KONAMI\MetalGearSolid2 Substance\bin\mgs2_sse.exe'

I don't think the fix neither the game support these strange characters in path.

Please reinstall the game into another path!

**Comment by bugo9870** [comment]
I tried but it still doesnt work.
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3555743/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
It seems that something is blocking the fix to replace the main game .exe. It can be some antivirus or some strange directory permission

Aside that be sure that the main game .exe isn't opened, you can extract manually the .exe fix instead.

You can try this:

* Download [THIS](https://github.com/VFansss/mgs2-v-s-fix/raw/master/mgs2%20v's%20fix/Resources/3_fixed_exe.zip) file (is the same that V's fix use internally)

* Extract the .zip content inside the 'bin' game folder. Overwrite when prompted (this is the operation that "something" is blocking")

* Create inside the 'bin' folder a file called "_fixed_exe_applied.sss" (without quotes, but with underscore. Mind the .sss extension).

Than re-open the fix, and send me the debug log if something doesn't work

**Comment by bugo9870** [comment]
The solution worked but after a while it fails to launch saying : " failed creating Direct3DDevice9 Object".
the debug doest update and keeps showing a former error I've already solved.
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3559576/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
> the debug doest update and keeps showing a former error I've already solved.

Well, from what I can see the debug is changed instead.

From what I can see from the debug log, the game (that you have tried to launch) can't access (in reading) the file that contain keyboard input mapping.

This make me think that you have severe permission issues, and something (windows? antivirus?) can't allow the executables (v's fix and the just extracted game .exe) to run correctly.

Is think isn't an issue directly correlated to V's fix, but whatever...

My advices are:

* Reinstall the game to another location (😭 )

* Download again the V's fix.

* After you finished the download, right click on the .zip file and select 'Properties'

* Uncheck this:

![immagine](https://user-images.githubusercontent.com/15073502/64060079-37b4bc00-cbc8-11e9-810b-23376a90abe4.png)

* Press "Apply"

Then proceed to install the fix and configure it like you have already done.

Also, everytime you send me a debug please do what is written on the [debug page](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#how-to-correctly-use-it) (aka "Press the SETTINGS -> SAVE" button before sending me the log)

**Comment by JakubJCz** [comment]
Same problem here but on Win7 Pro x64. 
![bug](https://user-images.githubusercontent.com/49360140/74109204-cc611400-4b81-11ea-9e2b-6259d47f49d6.jpg)
Just "Program mgs2 v's fix stopped working." mid patching with this files created.

Clean run:
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/4177743/MGS2_VFix_debug.txt)

After starting mgs2_sse.exe
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/4177757/MGS2_VFix_debug.txt)

But I have Win10 Home x64 installed too, and it goes through just fine. Even with this half patched folder. Working there normally.

**Comment by VFansss** [comment]
Ok, now this issue is mentioned and explained in the wiki.

I can't propertly address it, but isn't too hard to avoid it.

It's the I can do right now.

@JakubJCz This would worth its own issue 😢 Closing here...
