### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by rudatsurugen** [VFansss/mgs2-v-s-fix#99]
07.23.20.129 -> [!][!][!][!][!][!][!][!][!][!][!][!]
07.23.20.142 -> [!]
07.23.20.173 -> [!] Fix started at 12/09/2019 22:23:20 (UCT)
07.23.20.182 -> [!] Fix internal version: 190331
07.23.20.211 -> [!] V's Fix has admin rights
07.23.20.220 -> [RETRIEVE LAST.LOG] last.log not found
07.23.20.254 -> [PRINT LAST.LOG] No last.log file found. Game has never started!
07.23.20.258 -> [ ] Fixed exe not applied. Applying it
07.23.20.606 -> System.UnauthorizedAccessException: O acesso ao caminho 'C:\Users\Rudá\Desktop\JOGOS\MGS2\bin\mgs2_sse.exe' foi negado.
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   em System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   em mgs2_v_s_fix.Unzip.UnZippa(String fileToUnzip, Boolean OverWrite)
   em mgs2_v_s_fix.Program.Main(String[] args)
07.23.21.703 -> [!] Showed a messagebox with code: UAC_error
07.23.23.638 -> [!] Showed a messagebox with code: debugModeEnabled
07.23.23.640 -> [!] forbidStart is true. Closing.

**Comment by VFansss** [comment]
Something is blocking the Fix from patching the game .exe

[Follow what I wrote in another issue and tell me the results](https://github.com/VFansss/mgs2-v-s-fix/issues/97#issuecomment-526804887)

**Comment by VFansss** [comment]
I'm pretty confident that the things below would have solved the problem

Closing here...
